version: 2
updates:
  ## CosmosBackup
  - directory: "src/CosmosBackup"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  ## DataCleanup
  - directory: "src/DataCleanup"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  ## Storage
  - directory: "src/Storage"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Oslo"

  ## Storage.Interface
  - directory: "src/Storage.Interface"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Test
  - directory: "test/Altinn.Platform.Storage.Interface.Tests"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
  
  - directory: "test/UnitTest"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Dockerfile
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 10
