networks:
  altinnplatform_network:
    external: false

# Comment in the services for local development
services:
  # altinn_platform_storage:
  #   container_name: altinn-platform-storage
  #   image: altinnplatformstorage:latest
  #   restart: always
  #   networks:
  #     - altinnplatform_network
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:5010
  #     - PlatformStorageSettings:ApiEndPoint=http://altinn-platform-storage:5010/api/v1
  #     - PlatformStorageSettings:ApiEndPointHost=http://altinn-platform-storage:5010/
  #   ports:
  #     - "5010:5010"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  altinn_platform_storage_postgres:
    image: postgres:16
    container_name: storage_postgres
    restart: unless-stopped
    networks:
      - altinnplatform_network
    environment:
      - POSTGRES_USER=platform_storage_admin
      - POSTGRES_PASSWORD=Password
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  altinn_platform_storage_pgadmin:
    image: dpage/pgadmin4
    container_name: storage_pgadmin
    restart: unless-stopped
    networks:
      - altinnplatform_network
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: platform_storage_admin@altinn.no
      PGADMIN_DEFAULT_PASSWORD: Password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./infra/servers.json:/pgadmin4/servers.json

  altinn_platform_storage_azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    container_name: storage_azurite
    restart: unless-stopped
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - altinnplatform_network
