CREATE TABLE IF NOT EXISTS storage.outbox
(
	instanceid UUID PRIMARY KEY,
	appid TEXT NOT NULL,
	partyid INTEGER NOT NULL,
    created TIMESTAMPTZ NOT NULL,
    validfrom TIMESTAMPTZ NOT NULL,
    ismigration BOOLEAN NOT NULL DEFAULT FALSE,
    instanceeventtype SMALLINT NOT NULL DEFAULT 0
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS storage.leases (
    resource TEXT PRIMARY KEY,
    holder UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA storage TO platform_storage;
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA storage TO platform_storage_admin;