CREATE TABLE IF NOT EXISTS storage.instancelocks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    instanceinternalid BIGINT NOT NULL,
    lockedat TIMESTAMPTZ NOT NULL,
    lockeduntil TIMESTAMPTZ NOT NULL,
    lockedby TEXT NOT NULL,
    secrethash BYTEA NOT NULL
)
TABLESPACE pg_default;

GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON ALL TABLES IN SCHEMA storage TO platform_storage;
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON ALL TABLES IN SCHEMA storage TO platform_storage_admin;
