-- This script is autogenerated from the tool DbTools. Do not edit manually.

-- acquireinstancelock.sql:
CREATE OR REPLACE PROCEDURE storage.acquireinstancelock(
    _instanceinternalid BIGINT,
    _ttl INTERVAL,
    _lockedby TEXT,
    _secrethash BYTEA,
    INOUT _result TEXT DEFAULT NULL,
    INOUT _id BIGINT DEFAULT NULL
)
LANGUAGE plpgsql
AS $BODY$
DECLARE
    _lock_exists BOOLEAN;
    _now TIMESTAMPTZ;
BEGIN
    PERFORM pg_advisory_xact_lock(_instanceinternalid);

    SELECT clock_timestamp()
    INTO _now;

    SELECT true FROM storage.instancelocks
    WHERE instanceinternalid = _instanceinternalid
    AND lockeduntil > _now
    INTO _lock_exists;

    IF _lock_exists THEN
        _result := 'lock_held';
        RETURN;
    END IF;

    INSERT INTO storage.instancelocks (instanceinternalid, lockedat, lockeduntil, lockedby, secrethash)
    VALUES (_instanceinternalid, _now, _now + _ttl, _lockedby, _secrethash)
    RETURNING id INTO _id;

    _result := 'ok';
END;
$BODY$;


-- applyinstancemutation.sql:
CREATE OR REPLACE FUNCTION storage.applyinstancemutation(
    _instanceguid UUID,
    _instanceinternalid BIGINT,
    _expectedinstanceversion INT,
    _expectedprocessstateversion INT,
    _idempotencykey UUID,
    _lastchanged TIMESTAMPTZ,
    _lastchangedby TEXT,
    _createelements JSONB,
    _updateelements JSONB,
    _deleteelements JSONB,
    _instanceupdate JSONB,
    _events JSONB,
    _outbox JSONB
)
    RETURNS TABLE (
        replayed BOOLEAN,
        createddataelementids TEXT[],
        id BIGINT,
        instance JSONB,
        instanceversion INT,
        processstateversion INT,
        element JSONB,
        currentblobversion UUID
    )
    LANGUAGE plpgsql
AS $BODY$
DECLARE
    _currentinstanceversion INT;
    _currentprocessstateversion INT;
    _currentprocessstatus TEXT;
    _replaycreateddataelementids TEXT[];
    _committedcreateddataelementids TEXT[];
    _updatedids UUID[];
    _deletedids UUID[];
    -- Predicted post-mutation versions, computed upfront. The idempotency record stores
    -- the instance version; the final instance UPDATE assigns both. AM001 errors use the
    -- locked current versions instead, since the exception rolls back the mutation.
    _newinstanceversion INT;
    _newprocessstateversion INT;
    _composedinstance JSONB;
BEGIN
    SELECT
        i.instance,
        i.instance_version,
        i.process_state_version
    INTO _composedinstance, _currentinstanceversion, _currentprocessstateversion
    FROM storage.instances i
    WHERE i.id = _instanceinternalid
    FOR UPDATE;

    IF NOT FOUND
    THEN
        CALL storage.raiseinstancemutationerror(
            'instance_not_found',
            NULL::INT,
            NULL::INT);
    END IF;

    _currentprocessstatus := COALESCE(_composedinstance -> 'Process' ->> 'Status', 'idle');

    _createelements := COALESCE(_createelements, '[]'::JSONB);
    _updateelements := COALESCE(_updateelements, '[]'::JSONB);
    _deleteelements := COALESCE(_deleteelements, '[]'::JSONB);
    _events := COALESCE(_events, '[]'::JSONB);
    _committedcreateddataelementids := ARRAY[]::TEXT[];

    _newinstanceversion := CASE
        WHEN jsonb_array_length(_createelements) + jsonb_array_length(_updateelements) + jsonb_array_length(_deleteelements) > 0
            OR _instanceupdate IS NOT NULL
            THEN _currentinstanceversion + 1
        ELSE _currentinstanceversion
    END;

    _newprocessstateversion := CASE
        WHEN NULLIF(_instanceupdate -> 'process', 'null'::JSONB) IS NOT NULL
            THEN _currentprocessstateversion + 1
        ELSE _currentprocessstateversion
    END;

    SELECT COALESCE(array_agg(createelement.value ->> 'elementId' ORDER BY createelement.ordinality), ARRAY[]::TEXT[])
    INTO _committedcreateddataelementids
    FROM jsonb_array_elements(_createelements) WITH ORDINALITY createelement(value, ordinality);


    IF _idempotencykey IS NOT NULL AND _expectedinstanceversion IS NOT NULL
    THEN
        INSERT INTO storage.instance_mutation_idempotency
            (instance, previous_instance_version, idempotency_key, produced_instance_version, created_data_element_ids)
        VALUES
            (_instanceguid, _expectedinstanceversion, _idempotencykey, _newinstanceversion, _committedcreateddataelementids)
        ON CONFLICT (idempotency_key) DO NOTHING;

        IF NOT FOUND
        THEN
            _replaycreateddataelementids := storage.tryreplayinstancemutation(
                _idempotencykey,
                _instanceguid,
                _expectedinstanceversion,
                _currentinstanceversion,
                _currentprocessstateversion);

            RETURN QUERY
                SELECT true, _replaycreateddataelementids, r.id, r.instance, r.instanceversion, r.processstateversion, r.element, r.currentblobversion
                FROM storage.readinstance_v2(_instanceguid) r;
            RETURN;
        END IF;
    END IF;

    IF _expectedinstanceversion IS NOT NULL
        AND _currentinstanceversion <> _expectedinstanceversion
    THEN
        CALL storage.raiseinstancemutationerror(
            'instance_version_mismatch',
            _currentinstanceversion,
            _currentprocessstateversion);
    END IF;

    IF _expectedprocessstateversion IS NOT NULL
        AND _currentprocessstateversion <> _expectedprocessstateversion
    THEN
        CALL storage.raiseinstancemutationerror(
            'process_state_version_mismatch',
            _currentinstanceversion,
            _currentprocessstateversion);
    END IF;

    IF _currentprocessstatus <> 'idle'
        AND _expectedinstanceversion IS NULL
        AND _expectedprocessstateversion IS NULL
    THEN
        CALL storage.raiseinstancemutationerror(
            'process_status_conflict',
            _currentinstanceversion,
            _currentprocessstateversion,
            NULL::UUID,
            _currentprocessstatus);
    END IF;

    IF COALESCE((_composedinstance -> 'Status' ->> 'IsHardDeleted')::BOOLEAN, FALSE)
    THEN
        CALL storage.raiseinstancemutationerror(
            'instance_hard_deleted',
            _currentinstanceversion,
            _currentprocessstateversion);
    END IF;

    IF jsonb_array_length(_createelements) > 0
    THEN
        INSERT INTO storage.dataelements(instanceinternalid, instanceguid, alternateid, element, currentblobversion)
        SELECT
            _instanceinternalid,
            _instanceguid,
            createelement.dataelementid,
            jsonb_strip_nulls(
                createelement.element
                    || jsonb_build_object(
                        'LastChanged',
                        storage.timestamptz_to_jsonb_utc(_lastchanged),
                        'LastChangedBy',
                        _lastchangedby
                    )
            ),
            createelement.blobversion
        FROM (
            SELECT
                createelement.ordinality,
                (createelement.value ->> 'elementId')::UUID AS dataelementid,
                createelement.value -> 'element' AS element,
                (createelement.value ->> 'blobVersion')::UUID AS blobversion
            FROM jsonb_array_elements(_createelements) WITH ORDINALITY createelement(value, ordinality)
        ) createelement
        ORDER BY createelement.ordinality;

        UPDATE storage.dataelementblobversions dataelementblobversion
        SET detachedat = NULL
        FROM (
            SELECT
                (createelement.value ->> 'elementId')::UUID AS dataelementid,
                (createelement.value ->> 'blobVersion')::UUID AS blobversion
            FROM jsonb_array_elements(_createelements) createelement(value)
            WHERE createelement.value ->> 'blobVersion' IS NOT NULL
        ) createelement
        WHERE dataelementblobversion.id = createelement.blobversion
            AND dataelementblobversion.instanceguid = _instanceguid
            AND dataelementblobversion.dataelementid = createelement.dataelementid
            AND dataelementblobversion.detachedat IS NOT NULL;
    END IF;

    IF jsonb_array_length(_updateelements) > 0
    THEN
        -- Under READ COMMITTED, UPDATE re-evaluates this WHERE on the latest row
        -- version after taking the row lock (EvalPlanQual), so each row's
        -- check-and-write is atomic without a separate lock/validate statement.
        WITH updateelements AS (
            SELECT
                updateelement.ordinality,
                (updateelement.value ->> 'elementId')::UUID AS dataelementid,
                (updateelement.value ->> 'expectedBlobVersion')::UUID AS expectedblobversion,
                (updateelement.value ->> 'newBlobVersion')::UUID AS newblobversion,
                COALESCE((updateelement.value ->> 'ignoreLock')::BOOL, false) AS ignorelock,
                COALESCE(NULLIF(updateelement.value -> 'elementChanges', 'null'::JSONB), '{}'::JSONB) AS elementchanges
            FROM jsonb_array_elements(_updateelements) WITH ORDINALITY updateelement(value, ordinality)
        ),
        updated AS (
            UPDATE storage.dataelements dataelement
            SET element = dataelement.element
                    || updateelements.elementchanges
                    || CASE
                        WHEN updateelements.newblobversion IS NULL
                        THEN '{}'::JSONB
                        ELSE jsonb_build_object(
                            'LastChanged',
                            storage.timestamptz_to_jsonb_utc(_lastchanged),
                            'LastChangedBy',
                            COALESCE(to_jsonb(_lastchangedby), 'null'::JSONB)
                        )
                    END,
                currentblobversion = COALESCE(updateelements.newblobversion, dataelement.currentblobversion)
            FROM updateelements
            WHERE dataelement.instanceguid = _instanceguid
                AND dataelement.alternateid = updateelements.dataelementid
                AND (
                    updateelements.expectedblobversion IS NULL
                    OR dataelement.currentblobversion IS NOT DISTINCT FROM updateelements.expectedblobversion
                )
                AND NOT COALESCE((dataelement.element -> 'DeleteStatus' ->> 'IsHardDeleted')::BOOLEAN, FALSE)
                AND (
                    updateelements.ignorelock
                    OR NOT COALESCE((dataelement.element ->> 'Locked')::BOOLEAN, FALSE)
                )
            RETURNING dataelement.alternateid
        )
        SELECT COALESCE(array_agg(updated.alternateid), ARRAY[]::UUID[])
        INTO _updatedids
        FROM updated;

        IF cardinality(_updatedids) < jsonb_array_length(_updateelements)
        THEN
            CALL storage.diagnoseinstancemutationupdatefailure(
                _updateelements,
                _instanceguid,
                _currentinstanceversion,
                _currentprocessstateversion,
                _updatedids);
        END IF;

        -- Only one version per data element may be attached, and the partial unique index
        -- enforcing that is checked per statement, so the predecessors are detached first.
        UPDATE storage.dataelementblobversions superseded
        SET detachedat = NOW()
        FROM (
            SELECT (updateelement.value ->> 'elementId')::UUID AS dataelementid
            FROM jsonb_array_elements(_updateelements) updateelement(value)
            WHERE updateelement.value ->> 'newBlobVersion' IS NOT NULL
        ) updateelement
        WHERE superseded.instanceguid = _instanceguid
            AND superseded.dataelementid = updateelement.dataelementid
            AND superseded.detachedat IS NULL;

        UPDATE storage.dataelementblobversions dataelementblobversion
        SET detachedat = NULL
        FROM (
            SELECT
                (updateelement.value ->> 'elementId')::UUID AS dataelementid,
                (updateelement.value ->> 'newBlobVersion')::UUID AS newblobversion
            FROM jsonb_array_elements(_updateelements) updateelement(value)
            WHERE updateelement.value ->> 'newBlobVersion' IS NOT NULL
        ) updateelement
        WHERE dataelementblobversion.id = updateelement.newblobversion
            AND dataelementblobversion.instanceguid = _instanceguid
            AND dataelementblobversion.dataelementid = updateelement.dataelementid
            AND dataelementblobversion.detachedat IS NOT NULL;
    END IF;

    IF jsonb_array_length(_deleteelements) > 0
    THEN
        WITH deleteelements AS (
            SELECT
                (deleteelement.value ->> 'elementId')::UUID AS dataelementid,
                COALESCE((deleteelement.value ->> 'ignoreLock')::BOOL, false) AS ignorelock
            FROM jsonb_array_elements(_deleteelements) deleteelement(value)
        ),
        deleted AS (
            DELETE FROM storage.dataelements dataelement
            USING deleteelements deleteelement
            WHERE dataelement.instanceguid = _instanceguid
                AND dataelement.alternateid = deleteelement.dataelementid
                AND (
                    deleteelement.ignorelock
                    OR NOT COALESCE((dataelement.element ->> 'Locked')::BOOLEAN, FALSE)
                )
            RETURNING dataelement.alternateid
        )
        SELECT COALESCE(array_agg(deleted.alternateid), ARRAY[]::UUID[])
        INTO _deletedids
        FROM deleted;

        IF cardinality(_deletedids) < jsonb_array_length(_deleteelements)
        THEN
            CALL storage.diagnoseinstancemutationdeletefailure(
                _deleteelements,
                _instanceguid,
                _currentinstanceversion,
                _currentprocessstateversion,
                _deletedids);
        END IF;

        UPDATE storage.dataelementblobversions dataelementblobversion
        SET detachedat = NOW()
        FROM (
            SELECT (deleteelement.value ->> 'elementId')::UUID AS dataelementid
            FROM jsonb_array_elements(_deleteelements) deleteelement(value)
        ) deleteelement
        WHERE dataelementblobversion.instanceguid = _instanceguid
            AND dataelementblobversion.dataelementid = deleteelement.dataelementid
            AND dataelementblobversion.detachedat IS NULL;
    END IF;

    -- The upfront instance-version prediction is the any-operations signal.
    IF _newinstanceversion <> _currentinstanceversion
    THEN
        IF _composedinstance -> 'Status' ->> 'ReadStatus' = '1'
        THEN
            IF EXISTS (
                SELECT 1
                FROM jsonb_array_elements(_createelements) createelement(value)
                WHERE createelement.value -> 'element' ->> 'IsRead' = 'false'
            )
            THEN
                _composedinstance := jsonb_set(_composedinstance, '{Status, ReadStatus}', '2');
            ELSIF NOT EXISTS (
                SELECT 1
                FROM storage.dataelements dataelement
                WHERE dataelement.instanceguid = _instanceguid
                    AND dataelement.element -> 'IsRead' = 'true'
            )
            THEN
                _composedinstance := jsonb_set(_composedinstance, '{Status, ReadStatus}', '0');
            END IF;
        END IF;

        IF _instanceupdate IS NOT NULL
        THEN
            _composedinstance := storage.mergeinstanceupdate(_composedinstance, _instanceupdate);
        END IF;

        _composedinstance := _composedinstance
            || jsonb_set('{"LastChanged":""}', '{LastChanged}', storage.timestamptz_to_jsonb_utc(_lastchanged))
            || jsonb_set('{"LastChangedBy":""}', '{LastChangedBy}', COALESCE(to_jsonb(_lastchangedby), 'null'::JSONB));

        UPDATE storage.instances i
        SET instance = _composedinstance,
            lastchanged = _lastchanged,
            instance_version = _newinstanceversion,
            process_state_version = _newprocessstateversion,
            confirmed = COALESCE((_instanceupdate ->> 'confirmed')::BOOLEAN, i.confirmed),
            taskid = CASE
                WHEN NULLIF(_instanceupdate -> 'process', 'null'::JSONB) IS NOT NULL THEN _instanceupdate ->> 'taskid'
                ELSE i.taskid
            END
        WHERE i.id = _instanceinternalid;
    END IF;

    IF jsonb_array_length(_events) > 0
    THEN
        CALL storage.insertinstanceevents(_instanceguid, _events);
    END IF;

    IF _outbox IS NOT NULL
    THEN
        INSERT INTO storage.outbox
            (instanceid, appid, partyid, validfrom, instancecreated, ismigration, instanceeventtype)
        VALUES
            (
                _instanceguid,
                _outbox ->> 'appid',
                (_outbox ->> 'partyid')::BIGINT,
                clock_timestamp() + make_interval(secs => COALESCE((_outbox ->> 'delaySeconds')::DOUBLE PRECISION, 0)),
                (_outbox ->> 'instancecreated')::TIMESTAMPTZ,
                (_outbox ->> 'ismigration')::BOOLEAN,
                (_outbox ->> 'instanceeventtype')::SMALLINT
            )
        ON CONFLICT (instanceid) DO UPDATE SET
            validfrom = excluded.validfrom
        WHERE excluded.validfrom < storage.outbox.validfrom;
    END IF;

    RETURN QUERY
        SELECT false, _committedcreateddataelementids, r.id, r.instance, r.instanceversion, r.processstateversion, r.element, r.currentblobversion
        FROM storage.readinstance_v2(_instanceguid) r;
END;
$BODY$;


-- createblobversion.sql:
CREATE OR REPLACE FUNCTION storage.createblobversion(
    _id UUID,
    _instanceguid UUID,
    _dataelementid UUID,
    _appid TEXT,
    _blobstorageorg TEXT,
    _storageaccountnumber INT)
    RETURNS void
    LANGUAGE plpgsql
AS $BODY$
BEGIN
    INSERT INTO storage.dataelementblobversions(
        id,
        instanceguid,
        dataelementid,
        appid,
        blobstorageorg,
        storageaccountnumber,
        detachedat)
    VALUES (
        _id,
        _instanceguid,
        _dataelementid,
        _appid,
        _blobstorageorg,
        _storageaccountnumber,
        NOW());
END;
$BODY$;


-- deleteblobversion.sql:
CREATE OR REPLACE FUNCTION storage.deleteblobversion(_dataelementid UUID, _blobversionid UUID)
    RETURNS INT
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    DELETE FROM storage.dataelementblobversions
        WHERE id = _blobversionid
            AND dataelementid = _dataelementid
            AND detachedat IS NOT NULL;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;

    RETURN _deleteCount;
END;
$BODY$;


-- deleteblobversions.sql:
CREATE OR REPLACE FUNCTION storage.deleteblobversions(_dataelementid UUID, _blobversionids UUID[])
    RETURNS INT
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    DELETE FROM storage.dataelementblobversions
        WHERE id = ANY(_blobversionids)
            AND dataelementid = _dataelementid
            AND detachedat IS NOT NULL;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;

    RETURN _deleteCount;
END;
$BODY$;


-- deletedataelement.sql:
CREATE OR REPLACE FUNCTION storage.deletedataelement_v2(_alternateid UUID, _instanceGuid UUID, _lastChangedBy TEXT)
    RETURNS INT
    LANGUAGE 'plpgsql'	
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    IF (SELECT COUNT(*) FROM storage.dataelements WHERE element -> 'IsRead' = 'true' AND instanceguid = _instanceGuid) = 0 THEN
        UPDATE storage.instances
        SET instance = jsonb_set(instance, '{Status, ReadStatus}', '0')
        WHERE alternateid = _instanceGuid AND instance -> 'Status' ->> 'ReadStatus' = '1';
    END IF;

    UPDATE storage.instances
        SET lastchanged = NOW(),
            instance = instance
                || jsonb_set('{"LastChanged":""}', '{LastChanged}', to_jsonb(REPLACE((NOW() AT TIME ZONE 'UTC')::TEXT, ' ', 'T') || 'Z'))
                || jsonb_set('{"LastChangedBy":""}', '{LastChangedBy}', to_jsonb(_lastChangedBy))            
        WHERE alternateid = (SELECT instanceguid FROM storage.dataelements WHERE alternateid = _alternateid);

    DELETE FROM storage.dataelements WHERE alternateid = _alternateid;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;

    UPDATE storage.dataelementblobversions
        SET detachedat = NOW()
        WHERE instanceguid = _instanceGuid
            AND dataelementid = _alternateid
            AND detachedat IS NULL;

    RETURN _deleteCount;
END;
$BODY$;


-- deletedataelementforcleanup.sql:
CREATE OR REPLACE FUNCTION storage.deletedataelementforcleanup(_alternateid UUID, _instanceguid UUID)
    RETURNS INT
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    DELETE FROM storage.dataelements
        WHERE alternateid = _alternateid;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;

    UPDATE storage.dataelementblobversions
        SET detachedat = NOW()
        WHERE instanceguid = _instanceguid
            AND dataelementid = _alternateid
            AND detachedat IS NULL;

    RETURN _deleteCount;
END;
$BODY$;


-- deletedataelements.sql:
CREATE OR REPLACE FUNCTION storage.deletedataelements(_instanceguid UUID)
    RETURNS INT
    LANGUAGE 'plpgsql'	
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    UPDATE storage.instances
        SET lastchanged = NOW(),
            instance = instance
                || jsonb_set('{"LastChanged":""}', '{LastChanged}', to_jsonb(REPLACE((NOW() AT TIME ZONE 'UTC')::TEXT, ' ', 'T') || 'Z'))
                || jsonb_set('{"LastChangedBy":""}', '{LastChangedBy}', to_jsonb('altinn'::TEXT))   
        WHERE alternateid = _instanceguid;

    DELETE FROM storage.dataelements d
        USING storage.instances i
        WHERE i.alternateid = d.instanceguid AND i.alternateid = _instanceguid;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;

    UPDATE storage.dataelementblobversions
        SET detachedat = NOW()
        WHERE instanceguid = _instanceguid
            AND detachedat IS NULL;

    RETURN _deleteCount;
END;
$BODY$;


-- deleteinstance.sql:
CREATE OR REPLACE FUNCTION storage.deleteinstance(_alternateid UUID)
    RETURNS INT
    LANGUAGE 'plpgsql'	
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    DELETE FROM storage.instances WHERE alternateid = _alternateid;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;
    RETURN _deleteCount;
END;
$BODY$;

-- deleteinstanceevent.sql:
CREATE OR REPLACE FUNCTION storage.deleteinstanceevent(_instance UUID)
    RETURNS INT
    LANGUAGE 'plpgsql'	
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    DELETE FROM storage.instanceevents WHERE instance = _instance;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;
    RETURN _deleteCount;
END;
$BODY$;

-- deleteinstancemutationidempotency.sql:
CREATE OR REPLACE FUNCTION storage.deleteinstancemutationidempotency(_createdbefore TIMESTAMPTZ, _batchsize INT)
    RETURNS INT
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    DELETE FROM storage.instance_mutation_idempotency
        WHERE ctid IN (
            SELECT ctid
            FROM storage.instance_mutation_idempotency
            WHERE created < _createdbefore
            LIMIT _batchsize
        );
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;

    RETURN _deleteCount;
END;
$BODY$;


-- deletemigrationstate.sql:
CREATE OR REPLACE PROCEDURE storage.deletemigrationstate (_instanceguid UUID)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM storage.a1migrationstate WHERE instanceguid = _instanceguid;
	DELETE FROM storage.a2migrationstate WHERE instanceguid = _instanceguid;
END;
$BODY$;

-- deleteorphanblobversions.sql:
CREATE OR REPLACE FUNCTION storage.deleteorphanblobversions(_versions UUID[])
    RETURNS INT
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _deleteCount INTEGER;
BEGIN
    DELETE FROM storage.dataelementblobversions
        WHERE id = ANY(_versions)
            AND detachedat IS NOT NULL;
    GET DIAGNOSTICS _deleteCount = ROW_COUNT;

    RETURN _deleteCount;
END;
$BODY$;


-- diagnoseinstancemutationdeletefailure.sql:
CREATE OR REPLACE PROCEDURE storage.diagnoseinstancemutationdeletefailure(
    _deleteelements JSONB,
    _instanceguid UUID,
    _currentinstanceversion INT,
    _currentprocessstateversion INT,
    _deleteddataelementids UUID[])
LANGUAGE plpgsql
AS $BODY$
DECLARE
    _faileddataelementid UUID;
    _errorcode TEXT;
BEGIN
    WITH targetdataelements AS (
        SELECT *
        FROM (
            SELECT
                deleteelement.ordinality,
                (deleteelement.value ->> 'elementId')::UUID AS dataelementid,
                COALESCE((deleteelement.value ->> 'ignoreLock')::BOOL, false) AS ignorelock
            FROM jsonb_array_elements(_deleteelements) WITH ORDINALITY deleteelement(value, ordinality)
        ) deleteelements
        WHERE NOT COALESCE(
            deleteelements.dataelementid = ANY(_deleteddataelementids),
            false)
    ),
    targetdataelementstates AS (
        SELECT
            targetdataelements.ordinality,
            targetdataelements.dataelementid,
            targetdataelements.ignorelock,
            dataelement.alternateid IS NOT NULL AS targetexists,
            COALESCE((dataelement.element ->> 'Locked')::BOOLEAN, false) AS elementislocked
        FROM targetdataelements
        LEFT JOIN storage.dataelements dataelement
            ON dataelement.instanceguid = _instanceguid
            AND dataelement.alternateid = targetdataelements.dataelementid
    ),
    validationerrors AS (
        SELECT
            targetdataelementstates.ordinality,
            1 AS priority,
            targetdataelementstates.dataelementid,
            'data_element_not_found'::TEXT AS errorcode
        FROM targetdataelementstates
        WHERE NOT targetdataelementstates.targetexists

        UNION ALL

        SELECT
            targetdataelementstates.ordinality,
            2 AS priority,
            targetdataelementstates.dataelementid,
            'locked'::TEXT AS errorcode
        FROM targetdataelementstates
        WHERE targetdataelementstates.targetexists
            AND NOT targetdataelementstates.ignorelock
            AND targetdataelementstates.elementislocked
    )
    SELECT validationerrors.dataelementid, validationerrors.errorcode
    INTO _faileddataelementid, _errorcode
    FROM validationerrors
    ORDER BY validationerrors.ordinality, validationerrors.priority
    LIMIT 1;

    IF _errorcode IS NOT NULL
    THEN
        CALL storage.raiseinstancemutationerror(
            _errorcode,
            _currentinstanceversion,
            _currentprocessstateversion,
            _faileddataelementid);
        RETURN;
    END IF;

    RAISE EXCEPTION 'Apply instance mutation delete affected fewer data elements than expected, but no failing item could be identified.';
END;
$BODY$;


-- diagnoseinstancemutationupdatefailure.sql:
CREATE OR REPLACE PROCEDURE storage.diagnoseinstancemutationupdatefailure(
    _updateelements JSONB,
    _instanceguid UUID,
    _currentinstanceversion INT,
    _currentprocessstateversion INT,
    _updateddataelementids UUID[])
LANGUAGE plpgsql
AS $BODY$
DECLARE
    _faileddataelementid UUID;
    _errorcode TEXT;
BEGIN
    WITH targetdataelements AS (
        SELECT *
        FROM (
            SELECT
                updateelement.ordinality,
                (updateelement.value ->> 'elementId')::UUID AS dataelementid,
                (updateelement.value ->> 'expectedBlobVersion')::UUID AS expectedblobversion,
                COALESCE((updateelement.value ->> 'ignoreLock')::BOOL, false) AS ignorelock
            FROM jsonb_array_elements(_updateelements) WITH ORDINALITY updateelement(value, ordinality)
        ) updateelements
        WHERE NOT COALESCE(
            updateelements.dataelementid = ANY(_updateddataelementids),
            false)
    ),
    targetdataelementstates AS (
        SELECT
            targetdataelements.ordinality,
            targetdataelements.dataelementid,
            targetdataelements.expectedblobversion,
            targetdataelements.ignorelock,
            dataelement.alternateid IS NOT NULL AS targetexists,
            dataelement.currentblobversion,
            COALESCE((dataelement.element -> 'DeleteStatus' ->> 'IsHardDeleted')::BOOLEAN, false) AS elementisharddeleted,
            COALESCE((dataelement.element ->> 'Locked')::BOOLEAN, false) AS elementislocked
        FROM targetdataelements
        LEFT JOIN storage.dataelements dataelement
            ON dataelement.instanceguid = _instanceguid
            AND dataelement.alternateid = targetdataelements.dataelementid
    ),
    validationerrors AS (
        SELECT
            targetdataelementstates.ordinality,
            1 AS priority,
            targetdataelementstates.dataelementid,
            'data_element_not_found'::TEXT AS errorcode
        FROM targetdataelementstates
        WHERE NOT targetdataelementstates.targetexists

        UNION ALL

        SELECT
            targetdataelementstates.ordinality,
            2 AS priority,
            targetdataelementstates.dataelementid,
            'blob_version_mismatch'::TEXT AS errorcode
        FROM targetdataelementstates
        WHERE targetdataelementstates.targetexists
            AND targetdataelementstates.expectedblobversion IS NOT NULL
            AND targetdataelementstates.currentblobversion IS DISTINCT FROM targetdataelementstates.expectedblobversion

        UNION ALL

        SELECT
            targetdataelementstates.ordinality,
            3 AS priority,
            targetdataelementstates.dataelementid,
            'data_element_hard_deleted'::TEXT AS errorcode
        FROM targetdataelementstates
        WHERE targetdataelementstates.targetexists
            AND targetdataelementstates.elementisharddeleted

        UNION ALL

        SELECT
            targetdataelementstates.ordinality,
            4 AS priority,
            targetdataelementstates.dataelementid,
            'locked'::TEXT AS errorcode
        FROM targetdataelementstates
        WHERE targetdataelementstates.targetexists
            AND NOT targetdataelementstates.ignorelock
            AND targetdataelementstates.elementislocked
    )
    SELECT validationerrors.dataelementid, validationerrors.errorcode
    INTO _faileddataelementid, _errorcode
    FROM validationerrors
    ORDER BY validationerrors.ordinality, validationerrors.priority
    LIMIT 1;

    IF _errorcode IS NOT NULL
    THEN
        CALL storage.raiseinstancemutationerror(
            _errorcode,
            _currentinstanceversion,
            _currentprocessstateversion,
            _faileddataelementid);
        RETURN;
    END IF;

    RAISE EXCEPTION 'Apply instance mutation update affected fewer data elements than expected, but no failing item could be identified.';
END;
$BODY$;


-- filterinstanceevent.sql:
CREATE OR REPLACE FUNCTION storage.filterinstanceevent(_instance UUID, _from TIMESTAMPTZ, _to TIMESTAMPTZ, _eventtype TEXT[])
    RETURNS TABLE (event JSONB)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY 
    SELECT ie.event
    FROM storage.instanceevents ie
    WHERE instance = _instance
        AND (ie.event->>'Created')::TIMESTAMP >= _from
        AND (ie.event->>'Created')::TIMESTAMP <= _to
        AND (_eventtype IS NULL OR ie.event->>'EventType' = ANY (_eventtype))
    ORDER BY ie.event->'Created';
END;
$BODY$;

-- getinstancemetrics.sql:
CREATE OR REPLACE FUNCTION storage.get_instance_metrics(
    day_input integer,
    month_input integer,
    year_input integer)
    RETURNS TABLE (appid TEXT, completed_instances bigint)
    LANGUAGE 'plpgsql'

AS $BODY$
DECLARE
    start_date TIMESTAMPTZ;
BEGIN
    start_date = MAKE_TIMESTAMPTZ(year_input, month_input, day_input, 0, 0, 0, 'UTC');
    RETURN QUERY
        SELECT
            i.appid,
            count(i.id) AS CompletedInstances
        FROM storage.instances i
        WHERE (i.instance -> 'Status' ->> 'IsArchived')::BOOL = TRUE
            AND i.instance -> 'Status' ? 'Archived'
            AND NULLIF(i.instance -> 'Status' ->> 'Archived', '') IS NOT NULL
            AND storage.jsonb_text_to_timestamptz(i.instance, 'Status', 'Archived') >= start_date
            AND storage.jsonb_text_to_timestamptz(i.instance, 'Status', 'Archived') < start_date + INTERVAL '1 day'
            AND i.altinnmainversion = 3
        GROUP BY i.appid;
END;
$BODY$;


-- inserta1migrationstate.sql:
CREATE OR REPLACE PROCEDURE storage.inserta1migrationstate (_a1archiveReference BIGINT)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	INSERT INTO storage.a1migrationstate (a1archivereference) VALUES
		(_a1archiveReference)
	ON CONFLICT (a1archivereference) DO NOTHING;
END;
$BODY$;

-- inserta2codelist.sql:
CREATE OR REPLACE PROCEDURE storage.inserta2codelist (_name TEXT, _language TEXT, _version INT, _codelist TEXT)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
    INSERT INTO storage.a2codelists (name, language, version, codelist) VALUES
        (_name, _language, _version, _codelist)
		ON CONFLICT (name, language, version) DO UPDATE SET codelist = _codelist;	
END;
$BODY$;

-- inserta2image.sql:
CREATE OR REPLACE PROCEDURE storage.inserta2image (_name TEXT, _image BYTEA)
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _parentId INTEGER;
BEGIN
    SELECT id into _parentId FROM storage.a2images WHERE md5(_image) = md5(image);
    IF _parentId IS NOT NULL THEN
        INSERT INTO storage.a2images (name, parentid, image) VALUES
            (_name, _parentId, null)
			ON CONFLICT (name) DO NOTHING;
    ELSE
        INSERT INTO storage.a2images (name, parentid, image) VALUES
            (_name, null, _image)
			ON CONFLICT (name) DO UPDATE SET image = _image;
    END IF;
END;
$BODY$;

-- inserta2migrationstate.sql:
CREATE OR REPLACE PROCEDURE storage.inserta2migrationstate (_a2archiveReference BIGINT)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	INSERT INTO storage.a2migrationstate (a2archivereference) VALUES
		(_a2archiveReference)
	ON CONFLICT (a2archivereference) DO NOTHING;
END;
$BODY$;

-- inserta2xsl.sql:
CREATE OR REPLACE PROCEDURE storage.inserta2xsl (_org TEXT, _app TEXT, _lformid INT, _language TEXT, _pagenumber INT, _xsl TEXT, _xsltype INT, _isportrait BOOL)
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _parentId INTEGER;
    _appId INTEGER;
    _applicationinternalid INTEGER;
BEGIN
    SELECT id into _applicationinternalid FROM storage.applications WHERE org = _org AND app = _app;
    SELECT id into _parentId FROM storage.a2xsls WHERE org = _org AND app = _app AND xsl = _xsl AND xsltype = _xsltype;
    SELECT id into _appId FROM storage.applications WHERE org = _org AND app = _app;
    IF _parentId IS NOT NULL THEN
        INSERT INTO storage.a2xsls (org, app, applicationinternalid, parentid, lformid, language, pagenumber, xsl, xsltype, isportrait) VALUES
            (_org, _app, _applicationinternalid, _parentId, _lformid, _language, _pagenumber, NULL, _xsltype, _isportrait)
            ON CONFLICT (app, org, lformid, pagenumber, language, xsltype) DO NOTHING;
    ELSE
        INSERT INTO storage.a2xsls (org, app, applicationinternalid, parentid, lformid, language, pagenumber, xsl, xsltype, isportrait) VALUES
            (_org, _app, _applicationinternalid, NULL, _lformid, _language, _pagenumber, _xsl, _xsltype, _isportrait)
            ON CONFLICT (app, org, lformid, pagenumber, language, xsltype) DO UPDATE SET xsl = _xsl;			
    END IF;
END;
$BODY$;

-- insertdataelement.sql:
CREATE OR REPLACE FUNCTION storage.insertdataelement_v3(
    IN _instanceinternalid BIGINT,
    IN _instanceguid UUID,
    IN _alternateid UUID,
    IN _element JSONB,
    IN _currentblobversion UUID,
    IN _expectedinstanceversion INT DEFAULT NULL,
    IN _expectedprocessstateversion INT DEFAULT NULL)
    RETURNS TABLE (updatedElement JSONB, currentblobversion UUID, instanceversion INT, processstateversion INT, currentprocessstatus TEXT, result TEXT)
    LANGUAGE plpgsql
AS $BODY$
DECLARE
    _instanceIsHardDeleted BOOL;
    _currentInstanceVersion INT;
    _currentProcessStateVersion INT;
    _currentProcessStatus TEXT;
    _newInstanceVersion INT;
BEGIN
    SELECT
        COALESCE((i.instance -> 'Status' ->> 'IsHardDeleted')::BOOLEAN, FALSE),
        i.instance_version,
        i.process_state_version,
        COALESCE(i.instance -> 'Process' ->> 'Status', 'idle')
        INTO _instanceIsHardDeleted, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus
        FROM storage.instances i
        WHERE i.id = _instanceinternalid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, NULL::INT, NULL::INT, NULL::TEXT, 'not_found'::TEXT;
        RETURN;
    END IF;

    IF _expectedinstanceversion IS NOT NULL AND _currentInstanceVersion <> _expectedinstanceversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'instance_version_mismatch'::TEXT;
        RETURN;
    END IF;

    IF _expectedprocessstateversion IS NOT NULL AND _currentProcessStateVersion <> _expectedprocessstateversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'process_state_version_mismatch'::TEXT;
        RETURN;
    END IF;

    IF _instanceIsHardDeleted
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'hard_deleted'::TEXT;
        RETURN;
    END IF;

    IF _currentProcessStatus <> 'idle'
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'process_status_conflict'::TEXT;
        RETURN;
    END IF;

    IF _currentblobversion IS NOT NULL
    THEN
        UPDATE storage.dataelementblobversions
            SET detachedat = NULL
            WHERE id = _currentblobversion
                AND instanceguid = _instanceguid
                AND dataelementid = _alternateid
                AND detachedat IS NOT NULL;
    END IF;

    -- Make sure that lastChanged has the Postgres precision (6 digits). The timestamp from C# DateTime and then json serialize has 7 digits
    _element := _element || jsonb_set('{"LastChanged":""}', '{LastChanged}', storage.timestamptz_to_jsonb_utc((_element ->> 'LastChanged')::TIMESTAMPTZ));

    UPDATE storage.instances
        SET lastchanged = (_element ->> 'LastChanged')::TIMESTAMPTZ,
            instance_version = instance_version + 1,
            instance = (
                CASE
                    WHEN _element ->> 'IsRead' = 'false' AND instance -> 'Status' ->> 'ReadStatus' = '1'
                    THEN jsonb_set(instance, '{Status, ReadStatus}', '2')
                    ELSE instance
                END
            )
                || jsonb_set('{"LastChanged":""}', '{LastChanged}', to_jsonb(_element ->> 'LastChanged'))
                || jsonb_set('{"LastChangedBy":""}', '{LastChangedBy}', to_jsonb(_element ->> 'LastChangedBy'))
        WHERE id = _instanceinternalid
        RETURNING storage.instances.instance_version INTO _newInstanceVersion;

    RETURN QUERY
        INSERT INTO storage.dataelements(instanceinternalid, instanceGuid, alternateid, element, currentblobversion)
            VALUES (_instanceinternalid, _instanceGuid, _alternateid, jsonb_strip_nulls(_element), _currentblobversion)
            RETURNING element, storage.dataelements.currentblobversion, _newInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'ok'::TEXT;
END;
$BODY$;


-- insertinstance.sql:
CREATE OR REPLACE PROCEDURE storage.insertinstance_v3(_partyid BIGINT, _alternateid UUID, _instance JSONB, _created TIMESTAMPTZ, _lastchanged TIMESTAMPTZ, _org TEXT, _appid TEXT, _taskid TEXT, _altinnmainversion INT, _confirmed BOOLEAN)
    LANGUAGE 'plpgsql'	
AS $BODY$
BEGIN
    INSERT INTO storage.instances(partyid, alternateid, instance, created, lastchanged, org, appid, taskid, altinnmainversion, confirmed)
        VALUES (_partyid, _alternateid, jsonb_strip_nulls(_instance), _created, _lastchanged, _org, _appid, _taskid, _altinnmainversion, _confirmed);
END;
$BODY$;

-- insertinstanceevent.sql:
CREATE OR REPLACE PROCEDURE storage.insertinstanceevent(_instance UUID, _alternateid UUID, _event JSONB)
    LANGUAGE 'plpgsql'	
AS $BODY$
BEGIN
	-- Dummy comment to verify that new migration solution works end to end
	INSERT INTO storage.instanceevents(instance, alternateid, event) VALUES (_instance, _alternateid, jsonb_strip_nulls(_event));
END;
$BODY$;

-- insertinstanceevents.sql:

CREATE OR REPLACE PROCEDURE storage.insertinstanceevents(_instance UUID, _events JSONB)
    LANGUAGE 'plpgsql'	
AS $BODY$
BEGIN
	INSERT INTO storage.instanceevents (instance, alternateid, event)
	SELECT _instance, (evs->>'Id')::UUID, jsonb_strip_nulls(evs) 
	FROM jsonb_array_elements(_events) evs;
END;
$BODY$;

-- jsonbtexttotimestamptz.sql:
CREATE OR REPLACE FUNCTION storage.jsonb_text_to_timestamptz(data jsonb, key1 text, key2 text)
    RETURNS TIMESTAMPTZ
    LANGUAGE 'plpgsql' IMMUTABLE STRICT
AS $BODY$
BEGIN
  RETURN (data -> key1 ->> key2)::TIMESTAMPTZ;
END;
$BODY$;


-- mergeinstanceupdate.sql:
CREATE OR REPLACE FUNCTION storage.mergeinstanceupdate(
    _instance JSONB,
    _instanceupdate JSONB)
    RETURNS JSONB
    LANGUAGE SQL IMMUTABLE
AS $BODY$
    SELECT _instance || updateparts.toplevelsimpleprops
        || CASE
            WHEN updateparts.datavalues IS NOT NULL THEN
                jsonb_build_object(
                    'DataValues',
                    jsonb_strip_nulls(
                        COALESCE(_instance -> 'DataValues', '{}'::JSONB)
                            || updateparts.datavalues
                    )
                )
            ELSE
                '{}'::JSONB
        END
        || CASE
            WHEN updateparts.presentationtexts IS NOT NULL THEN
                jsonb_build_object(
                    'PresentationTexts',
                    jsonb_strip_nulls(
                        COALESCE(_instance -> 'PresentationTexts', '{}'::JSONB)
                            || updateparts.presentationtexts
                    )
                )
            ELSE
                '{}'::JSONB
        END
        || CASE
            WHEN updateparts.completeconfirmations IS NOT NULL THEN
                jsonb_build_object(
                    'CompleteConfirmations',
                    COALESCE(_instance -> 'CompleteConfirmations', '[]'::JSONB)
                        || (
                            SELECT COALESCE(jsonb_agg(incoming.value), '[]'::JSONB)
                            FROM jsonb_array_elements(updateparts.completeconfirmations) AS incoming
                            WHERE NOT EXISTS (
                                SELECT 1
                                FROM jsonb_array_elements(
                                    COALESCE(_instance -> 'CompleteConfirmations', '[]'::JSONB)
                                ) AS existing
                                WHERE existing.value ->> 'StakeholderId'
                                    = incoming.value ->> 'StakeholderId'
                            )
                        )
                )
            ELSE
                '{}'::JSONB
        END
        || CASE
            WHEN updateparts.status IS NOT NULL OR updateparts.substatus IS NOT NULL THEN
                jsonb_build_object(
                    'Status',
                    CASE
                        WHEN updateparts.substatus IS NOT NULL THEN
                            jsonb_set(
                                COALESCE(_instance -> 'Status', '{}'::JSONB)
                                    || COALESCE(updateparts.status, '{}'::JSONB),
                                '{Substatus}',
                                jsonb_strip_nulls(updateparts.substatus)
                            )
                        ELSE
                            COALESCE(_instance -> 'Status', '{}'::JSONB) || updateparts.status
                    END
                )
            ELSE
                '{}'::JSONB
        END
        || CASE
            WHEN updateparts.process IS NOT NULL THEN
                jsonb_build_object('Process', jsonb_strip_nulls(updateparts.process))
            ELSE
                '{}'::JSONB
        END
    FROM (
        SELECT
            COALESCE(NULLIF(_instanceupdate -> 'toplevelsimpleprops', 'null'::JSONB), '{}'::JSONB)
                - 'DataValues'
                - 'PresentationTexts'
                - 'CompleteConfirmations'
                - 'Status'
                - 'Process' AS toplevelsimpleprops,
            NULLIF(_instanceupdate -> 'datavalues', 'null'::JSONB) AS datavalues,
            NULLIF(_instanceupdate -> 'presentationtexts', 'null'::JSONB) AS presentationtexts,
            NULLIF(_instanceupdate -> 'completeconfirmations', 'null'::JSONB) AS completeconfirmations,
            NULLIF(_instanceupdate -> 'status', 'null'::JSONB) AS status,
            NULLIF(_instanceupdate -> 'substatus', 'null'::JSONB) AS substatus,
            NULLIF(_instanceupdate -> 'process', 'null'::JSONB) AS process
    ) updateparts;
$BODY$;


-- raiseinstancemutationerror.sql:
CREATE OR REPLACE PROCEDURE storage.raiseinstancemutationerror(
    _code TEXT,
    _currentinstanceversion INT,
    _currentprocessstateversion INT,
    _dataelementid UUID DEFAULT NULL,
    _currentprocessstatus TEXT DEFAULT NULL)
LANGUAGE plpgsql
AS $BODY$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = 'AM001',
        MESSAGE = json_build_object(
            'code', _code,
            'currentInstanceVersion', _currentinstanceversion,
            'currentProcessStateVersion', _currentprocessstateversion,
            'currentProcessStatus', _currentprocessstatus,
            'dataElementId', _dataelementid)::TEXT;
END;
$BODY$;


-- reada1migrationstate.sql:
CREATE OR REPLACE FUNCTION storage.reada1migrationstate(_a1archivereference BIGINT)
    RETURNS TABLE (instanceguid UUID)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY 
    SELECT ms.instanceguid FROM storage.a1migrationstate ms WHERE ms.a1archivereference = _a1archivereference;
END;
$BODY$;

-- reada2codelist.sql:
CREATE OR REPLACE FUNCTION storage.reada2codelist(_name TEXT, _language TEXT)
    RETURNS TABLE (codelist TEXT)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY
    SELECT c.codelist FROM storage.a2codelists c
        WHERE name ilike _name AND language = _language
        ORDER BY version DESC LIMIT 1;
END;
$BODY$;

-- reada2image.sql:
CREATE OR REPLACE FUNCTION storage.reada2image(_name TEXT)
    RETURNS TABLE (image BYTEA)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY
    SELECT
        CASE
            WHEN c.image IS NOT NULL THEN c.image
            ELSE (SELECT p.image FROM storage.a2images p WHERE p.id = c.parentid)
        END
    FROM storage.a2images c WHERE c.name = _name; 
END;
$BODY$;

-- reada2migrationstate.sql:
CREATE OR REPLACE FUNCTION storage.reada2migrationstate(_a2archivereference BIGINT)
    RETURNS TABLE (instanceguid UUID)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY 
    SELECT ms.instanceguid FROM storage.a2migrationstate ms WHERE ms.a2archivereference = _a2archivereference;
END;
$BODY$;

-- reada2xsls.sql:
CREATE OR REPLACE FUNCTION storage.reada2xsls(_org TEXT, _app TEXT, _lformid INT, _language TEXT, _xsltype INT)
    RETURNS TABLE (xsl TEXT, isportrait BOOL)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY 
    SELECT
        CASE
            WHEN x.xsl IS NOT NULL THEN x.xsl
            ELSE (SELECT p.xsl FROM storage.a2xsls p WHERE p.id = x.parentid)
        END,
        x.isportrait
        FROM storage.a2xsls x
        WHERE x.org = _org and x.app = _app and x.lformid = _lformid and x.language = _language and x.xsltype = _xsltype
        ORDER BY pagenumber;

END;
$BODY$;

-- readblobversions.sql:
CREATE OR REPLACE FUNCTION storage.readblobversions(_instanceguid UUID, _dataelementid UUID)
    RETURNS TABLE (instanceguid UUID, appid TEXT, blobstorageorg TEXT, storageaccountnumber INT, blobversions UUID[])
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
    RETURN QUERY
        SELECT
            bv.instanceguid,
            bv.appid,
            bv.blobstorageorg,
            bv.storageaccountnumber,
            array_agg(bv.id ORDER BY bv.created, bv.id) AS blobversions
        FROM storage.dataelementblobversions bv
        WHERE bv.instanceguid = _instanceguid
            AND bv.dataelementid = _dataelementid
            AND bv.detachedat IS NULL
        GROUP BY bv.instanceguid, bv.appid, bv.blobstorageorg, bv.storageaccountnumber
        ORDER BY min(bv.created), min(bv.id::TEXT);
END;
$BODY$;


-- readblobversionsforinstance.sql:
CREATE OR REPLACE FUNCTION storage.readblobversionsforinstance(_instanceguid UUID)
    RETURNS TABLE (dataelementid UUID, instanceguid UUID, appid TEXT, blobstorageorg TEXT, storageaccountnumber INT, blobversions UUID[])
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
    RETURN QUERY
        SELECT
            bv.dataelementid,
            bv.instanceguid,
            bv.appid,
            bv.blobstorageorg,
            bv.storageaccountnumber,
            array_agg(bv.id ORDER BY bv.created, bv.id) AS blobversions
        FROM storage.dataelementblobversions bv
        WHERE bv.instanceguid = _instanceguid
            AND bv.detachedat IS NULL
        GROUP BY bv.dataelementid, bv.instanceguid, bv.appid, bv.blobstorageorg, bv.storageaccountnumber
        ORDER BY min(bv.created), min(bv.id::TEXT);
END;
$BODY$;


-- readdataelement.sql:
CREATE OR REPLACE FUNCTION storage.readdataelement_v2(_alternateid UUID)
    RETURNS TABLE (element JSONB, currentblobversion UUID)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY 
    SELECT d.element, d.currentblobversion
    FROM storage.dataelements d
    WHERE d.alternateid = _alternateid;

END;
$BODY$;


-- readdataelementexists.sql:
CREATE OR REPLACE FUNCTION storage.readdataelementexists(_alternateid UUID)
    RETURNS TABLE (element BOOLEAN)
    LANGUAGE 'plpgsql'

AS $BODY$
BEGIN
RETURN QUERY
    SELECT EXISTS (
        SELECT 1
        FROM storage.dataelements de where de.alternateid = _alternateid
    );
END;
$BODY$;


-- readdeletedinstances.sql:
CREATE OR REPLACE FUNCTION storage.readdeletedinstances()
    RETURNS TABLE (instance JSONB)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY
    -- Make sure that part of the where clause is exactly as in filtered index instances_isharddeleted_and_more
    SELECT i.instance FROM storage.instances i
    WHERE (i.instance -> 'Status' -> 'IsHardDeleted')::BOOLEAN AND
    (
        NOT (i.instance -> 'Status' -> 'IsArchived')::BOOLEAN OR (i.instance -> 'CompleteConfirmations') IS NOT NULL
    )
    -- Keep hard-deleted instance rows past the workflow callback retry window so delete mutations can replay.
    AND (i.instance -> 'Status' ->> 'HardDeleted')::TIMESTAMPTZ <= (NOW() - INTERVAL '7 days')
    AND i.AltinnMainVersion >= 3;
END;
$BODY$;


-- readdetachedblobversions.sql:
CREATE OR REPLACE FUNCTION storage.readdetachedblobversions(_dataelementid UUID)
    RETURNS TABLE (instanceguid UUID, appid TEXT, blobstorageorg TEXT, storageaccountnumber INT, blobversions UUID[])
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
    RETURN QUERY
        SELECT
            bv.instanceguid,
            bv.appid,
            bv.blobstorageorg,
            bv.storageaccountnumber,
            array_agg(bv.id ORDER BY bv.created, bv.id) AS blobversions
        FROM storage.dataelementblobversions bv
        WHERE bv.dataelementid = _dataelementid
            AND bv.detachedat IS NOT NULL
        GROUP BY bv.instanceguid, bv.appid, bv.blobstorageorg, bv.storageaccountnumber
        ORDER BY min(bv.created), min(bv.id::TEXT);
END;
$BODY$;


-- readharddeleteddataelementsforcleanup.sql:
CREATE OR REPLACE FUNCTION storage.readharddeleteddataelementsforcleanup()
    RETURNS TABLE (
        id BIGINT,
        instance JSONB,
        element JSONB,
        blobversioninstanceguid UUID,
        blobversionappid TEXT,
        blobversionblobstorageorg TEXT,
        blobversionstorageaccountnumber INT,
        blobversions UUID[])
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
    -- Force nested loop join to avoid hash join on large instances table
    -- With only a small count of hard-deleted records, nested loop with index lookups is optimal
    SET LOCAL enable_hashjoin = off;
    SET LOCAL enable_mergejoin = off;

    RETURN QUERY
    SELECT
        i.id,
        i.instance,
        d.element,
        v.instanceguid,
        v.appid,
        v.blobstorageorg,
        v.storageaccountnumber,
        COALESCE(v.blobversions, ARRAY[]::UUID[])
    FROM (
        -- Target index dataelements_isharddeleted
        SELECT instanceinternalid, de.alternateid, de.element
        FROM storage.dataelements de
        WHERE (de.element -> 'DeleteStatus' -> 'IsHardDeleted')::BOOLEAN
            AND (de.element -> 'DeleteStatus' ->> 'HardDeleted')::TIMESTAMPTZ <= NOW() - INTERVAL '7 days'
        OFFSET 0  -- Optimization fence: prevents subquery flattening which causes wrong join strategy
    ) d
    JOIN storage.instances i ON i.id = d.instanceinternalid
    LEFT JOIN LATERAL (
        SELECT
            bv.instanceguid,
            bv.appid,
            bv.blobstorageorg,
            bv.storageaccountnumber,
            array_agg(bv.id ORDER BY bv.created, bv.id) AS blobversions
        FROM storage.dataelementblobversions bv
        WHERE bv.instanceguid = i.alternateid
            AND bv.dataelementid = d.alternateid
            AND bv.detachedat IS NULL
        GROUP BY bv.instanceguid, bv.appid, bv.blobstorageorg, bv.storageaccountnumber
    ) v ON TRUE
    WHERE i.AltinnMainVersion >= 3;
END;
$BODY$;


-- readinstance.sql:
CREATE OR REPLACE FUNCTION storage.readinstance_v2(_alternateid UUID)
    RETURNS TABLE (id BIGINT, instance JSONB, instanceversion INT, processstateversion INT, element JSONB, currentblobversion UUID)
    LANGUAGE 'plpgsql'

AS $BODY$
BEGIN
RETURN QUERY
    SELECT i.id, i.instance, i.instance_version, i.process_state_version, d.element, d.currentblobversion FROM storage.instances i
        LEFT JOIN storage.dataelements d ON i.id = d.instanceinternalid
        WHERE i.alternateid = _alternateid
        ORDER BY d.id;

END;
$BODY$;


-- readinstanceevent.sql:
CREATE OR REPLACE FUNCTION storage.readinstanceevent_v2(_instance UUID, _alternateid UUID)
    RETURNS TABLE (event JSONB)
    LANGUAGE 'plpgsql'
    
AS $BODY$
BEGIN
RETURN QUERY 
    SELECT ie.event FROM storage.instanceevents ie
        WHERE ie.alternateid = _alternateid AND ie.instance = _instance;

END;
$BODY$;


-- readinstancefromquery.sql:
CREATE OR REPLACE FUNCTION storage.readinstancefromquery_v9(
    _a3_reference TEXT DEFAULT NULL,
    _appId TEXT DEFAULT NULL,
    _appIds TEXT[] DEFAULT NULL,
    _archiveReference TEXT DEFAULT NULL,
    _confirmed BOOLEAN DEFAULT NULL,
    _continue_idx BIGINT DEFAULT 0,
    _created_eq TIMESTAMPTZ DEFAULT NULL,
    _created_gt TIMESTAMPTZ DEFAULT NULL,
    _created_gte TIMESTAMPTZ DEFAULT NULL,
    _created_lt TIMESTAMPTZ DEFAULT NULL,
    _created_lte TIMESTAMPTZ DEFAULT NULL,
    _dataValues_A2ArchRef TEXT DEFAULT NULL,
    _dueBefore_eq TEXT DEFAULT NULL,
    _dueBefore_gt TEXT DEFAULT NULL,
    _dueBefore_gte TEXT DEFAULT NULL,
    _dueBefore_lt TEXT DEFAULT NULL,
    _dueBefore_lte TEXT DEFAULT NULL,
    _excludeConfirmedBy JSONB[] DEFAULT NULL,
    _includeElements BOOL DEFAULT TRUE,
    _instanceOwner_partyId INTEGER DEFAULT NULL,
    _instanceOwner_partyIds INTEGER[] DEFAULT NULL,
    _lastChanged_eq TIMESTAMPTZ DEFAULT NULL,
    _lastChanged_gt TIMESTAMPTZ DEFAULT NULL,
    _lastChanged_gte TIMESTAMPTZ DEFAULT NULL,
    _lastChanged_idx TIMESTAMPTZ DEFAULT NULL,
    _lastChanged_lt TIMESTAMPTZ DEFAULT NULL,
    _lastChanged_lte TIMESTAMPTZ DEFAULT NULL,
    _mainVersionInclude SMALLINT DEFAULT NULL,
    _mainVersionExclude SMALLINT DEFAULT NULL,
    _msgBoxInterval_eq TIMESTAMPTZ DEFAULT NULL,
    _msgBoxInterval_gt TIMESTAMPTZ DEFAULT NULL,
    _msgBoxInterval_gte TIMESTAMPTZ DEFAULT NULL,
    _msgBoxInterval_lt TIMESTAMPTZ DEFAULT NULL,
    _msgBoxInterval_lte TIMESTAMPTZ DEFAULT NULL,
    _org TEXT DEFAULT NULL,
    _process_currentTask TEXT DEFAULT NULL,
    _process_ended_eq TEXT DEFAULT NULL,
    _process_ended_gt TEXT DEFAULT NULL,
    _process_ended_gte TEXT DEFAULT NULL,
    _process_ended_lt TEXT DEFAULT NULL,
    _process_ended_lte TEXT DEFAULT NULL,
    _process_isComplete BOOLEAN DEFAULT NULL,
    _search_string TEXT DEFAULT NULL,
    _size INTEGER DEFAULT 100,
    _sort_ascending BOOLEAN DEFAULT FALSE,
    _status_isActiveOrSoftDeleted BOOLEAN  DEFAULT NULL,
    _status_isArchived BOOLEAN DEFAULT NULL,
    _status_isArchivedOrSoftDeleted BOOLEAN DEFAULT NULL,
    _status_isHardDeleted BOOLEAN DEFAULT NULL,
    _status_isSoftDeleted BOOLEAN DEFAULT NULL,
    _visibleAfter_eq TEXT DEFAULT NULL,
    _visibleAfter_gt TEXT DEFAULT NULL,
    _visibleAfter_gte TEXT DEFAULT NULL,
    _visibleAfter_lt TEXT DEFAULT NULL,
    _visibleAfter_lte TEXT DEFAULT NULL
    )
    RETURNS TABLE (id BIGINT, instance JSONB, instanceversion INT, processstateversion INT, element JSONB, currentblobversion UUID)
    LANGUAGE 'plpgsql'

AS $BODY$
BEGIN
    IF _sort_ascending IS NULL THEN
        _sort_ascending := false;
    END IF;

    RETURN QUERY
    WITH filteredInstances AS
    (
        SELECT i.id, i.instance, i.lastchanged, i.instance_version, i.process_state_version FROM storage.instances i
        WHERE 1 = 1
            AND (_a3_reference IS NULL OR right(i.alternateid::text, 12) = lower(_a3_reference))
            AND (_confirmed IS NULL OR _confirmed = confirmed)
            AND (_continue_idx <= 0 OR
                (_continue_idx > 0 AND _sort_ascending = true  AND (i.lastchanged > _lastChanged_idx OR (i.lastchanged = _lastChanged_idx AND i.id > _continue_idx))) OR
                (_continue_idx > 0 AND _sort_ascending = false AND (i.lastchanged < _lastChanged_idx OR (i.lastchanged = _lastChanged_idx AND i.id < _continue_idx))))
            AND (_appId IS NULL OR i.appid = _appId)
            AND (_archiveReference IS NULL OR i.instance ->> 'Id' like '%' || _archiveReference)
            AND (_created_gte IS NULL OR i.created >= _created_gte)
            AND (_created_gt  IS NULL OR i.created >  _created_gt)
            AND (_created_lte IS NULL OR i.created <= _created_lte)
            AND (_created_lt  IS NULL OR i.created <  _created_lt)
            AND (_created_eq  IS NULL OR i.created =  _created_eq)
            AND (_dataValues_A2ArchRef IS NULL OR i.instance -> 'DataValues' ->> 'A2ArchRef' = _dataValues_A2ArchRef)
            AND (_dueBefore_gte IS NULL OR i.instance ->> 'DueBefore' >= _dueBefore_gte)
            AND (_dueBefore_gt  IS NULL OR i.instance ->> 'DueBefore' >  _dueBefore_gt)
            AND (_dueBefore_lte IS NULL OR i.instance ->> 'DueBefore' <= _dueBefore_lte)
            AND (_dueBefore_lt  IS NULL OR i.instance ->> 'DueBefore' <  _dueBefore_lt)
            AND (_dueBefore_eq   IS NULL OR i.instance ->> 'DueBefore' =  _dueBefore_eq)
            AND (_excludeConfirmedBy IS NULL OR i.instance -> 'CompleteConfirmations' IS NULL OR NOT i.instance -> 'CompleteConfirmations' @> ANY (_excludeConfirmedBy))
            AND (_instanceOwner_partyId IS NULL OR partyId = _instanceOwner_partyId)
            AND (_instanceOwner_partyIds IS NULL OR partyId = ANY(_instanceOwner_partyIds))
            AND (_lastChanged_gte IS NULL OR i.lastchanged >= _lastChanged_gte)
            AND (_lastChanged_gt  IS NULL OR i.lastchanged >  _lastChanged_gt)
            AND (_lastChanged_lte IS NULL OR i.lastchanged <= _lastChanged_lte)
            AND (_lastChanged_lt  IS NULL OR i.lastchanged <  _lastChanged_lt)
            AND (_lastChanged_eq  IS NULL OR i.lastchanged =  _lastChanged_eq)
            AND (_mainVersionInclude IS NULL OR i.altinnmainversion = _mainVersionInclude)
            AND (_mainVersionExclude IS NULL OR i.altinnmainversion <> _mainVersionExclude)
            AND (_msgBoxInterval_gte IS NULL OR ((i.instance -> 'Status' -> 'IsArchived')::boolean = false AND i.created >= _msgBoxInterval_gte OR (i.instance -> 'Status' -> 'IsArchived')::boolean = true  AND i.lastchanged >= _msgBoxInterval_gte))
            AND (_msgBoxInterval_gt  IS NULL OR ((i.instance -> 'Status' -> 'IsArchived')::boolean = false AND i.created >  _msgBoxInterval_gt  OR (i.instance -> 'Status' -> 'IsArchived')::boolean = true  AND i.lastchanged >  _msgBoxInterval_gt))
            AND (_msgBoxInterval_lte IS NULL OR ((i.instance -> 'Status' -> 'IsArchived')::boolean = false AND i.created <= _msgBoxInterval_lte OR (i.instance -> 'Status' -> 'IsArchived')::boolean = true  AND i.lastchanged <= _msgBoxInterval_lte))
            AND (_msgBoxInterval_lt  IS NULL OR ((i.instance -> 'Status' -> 'IsArchived')::boolean = false AND i.created <  _msgBoxInterval_lt  OR (i.instance -> 'Status' -> 'IsArchived')::boolean = true  AND i.lastchanged <  _msgBoxInterval_lt))
            AND (_msgBoxInterval_eq  IS NULL OR ((i.instance -> 'Status' -> 'IsArchived')::boolean = false AND i.created =  _msgBoxInterval_eq  OR (i.instance -> 'Status' -> 'IsArchived')::boolean = true  AND i.lastchanged =  _msgBoxInterval_eq))
            AND (_org IS NULL OR i.org = _org)
            AND (_process_currentTask IS NULL OR i.taskid = _process_currentTask)
            AND (_process_ended_gte IS NULL OR i.instance -> 'Process' ->> 'Ended' >= _process_ended_gte)
            AND (_process_ended_gt  IS NULL OR i.instance -> 'Process' ->> 'Ended' >  _process_ended_gt)
            AND (_process_ended_lte IS NULL OR i.instance -> 'Process' ->> 'Ended' <= _process_ended_lte)
            AND (_process_ended_lt  IS NULL OR i.instance -> 'Process' ->> 'Ended' <  _process_ended_lt)
            AND (_process_ended_eq  IS NULL OR i.instance -> 'Process' ->> 'Ended' =  _process_ended_eq)
            AND (_process_isComplete IS NULL OR (_process_isComplete = TRUE AND i.instance -> 'Process' -> 'Ended' IS NOT NULL) OR (_process_isComplete = FALSE AND i.instance -> 'Process' -> 'CurrentTask' IS NOT NULL))
            AND (_search_string IS NULL OR (i.appid = ANY(_appIds) OR (EXISTS (SELECT value FROM jsonb_each_text(i.instance -> 'PresentationTexts') WHERE value ilike _search_string))))
            AND ((_status_isActiveOrSoftDeleted IS NULL OR _status_isActiveOrSoftDeleted = false) OR ((i.instance -> 'Status' -> 'IsArchived')::boolean = false OR (i.instance -> 'Status' -> 'IsSoftDeleted')::boolean = true))
            AND (_status_isArchived IS NULL OR  (i.instance -> 'Status' -> 'IsArchived')::boolean = _status_isArchived)
            AND ((_status_isArchivedOrSoftDeleted IS NULL OR _status_isArchivedOrSoftDeleted = false) OR ((i.instance -> 'Status' -> 'IsArchived')::boolean = true OR (i.instance -> 'Status' -> 'IsSoftDeleted')::boolean = true))
            AND (_status_isHardDeleted IS NULL OR  (i.instance -> 'Status' -> 'IsHardDeleted')::boolean = _status_isHardDeleted)
            AND (_status_isSoftDeleted IS NULL OR  (i.instance -> 'Status' -> 'IsSoftDeleted')::boolean = _status_isSoftDeleted)
            AND (_visibleAfter_gte IS NULL OR i.instance ->> 'VisibleAfter' >= _visibleAfter_gte)
            AND (_visibleAfter_gt  IS NULL OR i.instance ->> 'VisibleAfter' >  _visibleAfter_gt)
            AND (_visibleAfter_lte IS NULL OR i.instance ->> 'VisibleAfter' <= _visibleAfter_lte)
            AND (_visibleAfter_lt  IS NULL OR i.instance ->> 'VisibleAfter' <  _visibleAfter_lt)
            AND (_visibleAfter_eq  IS NULL OR i.instance ->> 'VisibleAfter' =  _visibleAfter_eq)
        ORDER BY
            (CASE WHEN _sort_ascending = true  THEN i.lastChanged END) ASC,
            (CASE WHEN _sort_ascending = false THEN i.lastChanged END) DESC,
            i.id
        FETCH FIRST _size ROWS ONLY
    )
        SELECT filteredInstances.id, filteredInstances.instance, filteredInstances.instance_version, filteredInstances.process_state_version, d.element, d.currentblobversion FROM filteredInstances
            LEFT JOIN storage.dataelements d ON filteredInstances.id = d.instanceInternalId AND _includeElements = TRUE
        ORDER BY
            (CASE WHEN _sort_ascending = true  THEN filteredInstances.lastChanged END) ASC,
            (CASE WHEN _sort_ascending = false THEN filteredInstances.lastChanged END) DESC,
            filteredInstances.id,
            d.id;
END;
$BODY$;


-- readinstancenoelements.sql:
CREATE OR REPLACE FUNCTION storage.readinstancenoelements_v2(_alternateid UUID)
    RETURNS TABLE (id BIGINT, instance JSONB, instanceversion INT, processstateversion INT)
    LANGUAGE 'plpgsql'

AS $BODY$
BEGIN
RETURN QUERY
    SELECT i.id, i.instance, i.instance_version, i.process_state_version FROM storage.instances i
        WHERE i.alternateid = _alternateid;
END;
$BODY$;


-- readorphanblobversionsforcleanup.sql:
CREATE OR REPLACE FUNCTION storage.readorphanblobversionsforcleanup()
    RETURNS TABLE (instanceguid UUID, appid TEXT, blobstorageorg TEXT, storageaccountnumber INT, blobversions UUID[])
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
    RETURN QUERY
        SELECT
            v.instanceguid,
            v.appid,
            v.blobstorageorg,
            v.storageaccountnumber,
            array_agg(v.id ORDER BY v.created, v.id) AS blobversions
        FROM storage.dataelementblobversions v
        WHERE v.detachedat <= NOW() - INTERVAL '7 days'
        GROUP BY v.instanceguid, v.appid, v.blobstorageorg, v.storageaccountnumber;
END;
$BODY$;


-- timestamptztojsonbutc.sql:
CREATE OR REPLACE FUNCTION storage.timestamptz_to_jsonb_utc(_timestamp TIMESTAMPTZ)
    RETURNS JSONB
    LANGUAGE 'plpgsql' IMMUTABLE
AS $BODY$
BEGIN
  RETURN COALESCE(to_jsonb(REPLACE((_timestamp AT TIME ZONE 'UTC')::TEXT, ' ', 'T') || 'Z'), 'null'::JSONB);
END;
$BODY$;


-- tryreplayinstancemutation.sql:
CREATE OR REPLACE FUNCTION storage.tryreplayinstancemutation(
    IN _idempotencykey UUID,
    IN _instanceguid UUID,
    IN _previousinstanceversion INT,
    IN _currentinstanceversion INT,
    IN _currentprocessstateversion INT)
    RETURNS TEXT[]
    LANGUAGE plpgsql
AS $BODY$
DECLARE
    _producedinstanceversion INT;
    _createddataelementids TEXT[];
    _storedinstanceguid UUID;
    _storedpreviousinstanceversion INT;
BEGIN
    SELECT
        i.instance,
        i.previous_instance_version,
        i.produced_instance_version,
        i.created_data_element_ids
        INTO
            _storedinstanceguid,
            _storedpreviousinstanceversion,
            _producedinstanceversion,
            _createddataelementids
        FROM storage.instance_mutation_idempotency i
        WHERE i.idempotency_key = _idempotencykey;

    IF NOT FOUND
    THEN
        CALL storage.raiseinstancemutationerror(
            'idempotency_key_not_found',
            _currentinstanceversion,
            _currentprocessstateversion);
    END IF;

    IF _storedinstanceguid IS DISTINCT FROM _instanceguid
    THEN
        CALL storage.raiseinstancemutationerror(
            'idempotency_key_instance_mismatch',
            _currentinstanceversion,
            _currentprocessstateversion);
    END IF;

    IF _storedpreviousinstanceversion IS DISTINCT FROM _previousinstanceversion
    THEN
        CALL storage.raiseinstancemutationerror(
            'instance_version_mismatch',
            _currentinstanceversion,
            _currentprocessstateversion);
    END IF;

    IF _currentinstanceversion > _producedinstanceversion
    THEN
        CALL storage.raiseinstancemutationerror(
            'instance_already_advanced',
            _currentinstanceversion,
            _currentprocessstateversion);
    END IF;

    RETURN _createddataelementids;
END;
$BODY$;


-- updatea1migrationstatestarted.sql:
CREATE OR REPLACE PROCEDURE storage.updatea1migrationstatestarted (_a1archivereference BIGINT, _instanceguid UUID)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	UPDATE storage.a1migrationstate SET instanceguid = _instanceguid, started = now()
		WHERE a1archivereference = _a1archivereference;
END;
$BODY$;

-- updatea2migrationstatestarted.sql:
CREATE OR REPLACE PROCEDURE storage.updatea2migrationstatestarted (_a2archivereference BIGINT, _instanceguid UUID)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	UPDATE storage.a2migrationstate SET instanceguid = _instanceguid, started = now()
		WHERE a2archivereference = _a2archivereference;
END;
$BODY$;

-- updatedataelement_filescanstatus.sql:
CREATE OR REPLACE FUNCTION storage.updatedataelement_filescanstatus(
    _dataelementGuid UUID,
    _instanceGuid UUID,
    _elementChanges JSONB,
    _expectedcurrentblobversion UUID)
    RETURNS TABLE (updatedElement JSONB, currentblobversion UUID, instanceversion INT, processstateversion INT, result TEXT)
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _currentInstanceVersion INT;
    _currentProcessStateVersion INT;
    _dataElementCurrentBlobVersion UUID;
BEGIN
    SELECT
        i.instance_version,
        i.process_state_version
        INTO _currentInstanceVersion, _currentProcessStateVersion
        FROM storage.instances i
        WHERE i.alternateid = _instanceGuid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, NULL::INT, NULL::INT, 'not_found'::TEXT;
        RETURN;
    END IF;

    SELECT d.currentblobversion
        INTO _dataElementCurrentBlobVersion
        FROM storage.dataelements d
        WHERE d.alternateid = _dataelementGuid AND d.instanceguid = _instanceGuid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, 'not_found'::TEXT;
        RETURN;
    END IF;

    IF _expectedcurrentblobversion IS NOT NULL AND _dataElementCurrentBlobVersion IS DISTINCT FROM _expectedcurrentblobversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, 'version_mismatch'::TEXT;
        RETURN;
    END IF;

    RETURN QUERY
        UPDATE storage.dataelements
            SET element = element || _elementChanges
            WHERE alternateid = _dataelementGuid AND instanceguid = _instanceGuid
            RETURNING element, storage.dataelements.currentblobversion, _currentInstanceVersion, _currentProcessStateVersion, 'ok'::TEXT;
END;
$BODY$;


-- updatedataelement_lockstatus.sql:
CREATE OR REPLACE FUNCTION storage.updatedataelement_lockstatus(
    _dataelementGuid UUID,
    _instanceGuid UUID,
    _locked BOOL)
    RETURNS TABLE (updatedElement JSONB, currentblobversion UUID, instanceversion INT, processstateversion INT, currentprocessstatus TEXT, result TEXT)
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _currentInstanceVersion INT;
    _currentProcessStateVersion INT;
    _currentProcessStatus TEXT;
BEGIN
    SELECT
        i.instance_version,
        i.process_state_version,
        COALESCE(i.instance -> 'Process' ->> 'Status', 'idle')
        INTO _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus
        FROM storage.instances i
        WHERE i.alternateid = _instanceGuid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, NULL::INT, NULL::INT, NULL::TEXT, 'not_found'::TEXT;
        RETURN;
    END IF;

    PERFORM 1
        FROM storage.dataelements d
        WHERE d.alternateid = _dataelementGuid AND d.instanceguid = _instanceGuid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'not_found'::TEXT;
        RETURN;
    END IF;

    IF _currentProcessStatus <> 'idle'
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'process_status_conflict'::TEXT;
        RETURN;
    END IF;

    RETURN QUERY
        UPDATE storage.dataelements
            SET element = element || jsonb_build_object('Locked', _locked)
            WHERE alternateid = _dataelementGuid AND instanceguid = _instanceGuid
            RETURNING element, storage.dataelements.currentblobversion, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'ok'::TEXT;
END;
$BODY$;


-- updatedataelement_readstatus.sql:
CREATE OR REPLACE FUNCTION storage.updatedataelement_readstatus(
    _dataelementGuid UUID,
    _instanceGuid UUID,
    _isRead BOOL)
    RETURNS TABLE (updatedElement JSONB, currentblobversion UUID, instanceversion INT, processstateversion INT, result TEXT)
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _currentInstanceVersion INT;
    _currentProcessStateVersion INT;
    _updatedElement JSONB;
    _currentBlobVersion UUID;
BEGIN
    SELECT i.instance_version, i.process_state_version
        INTO _currentInstanceVersion, _currentProcessStateVersion
        FROM storage.instances i
        WHERE i.alternateid = _instanceGuid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, NULL::INT, NULL::INT, 'not_found'::TEXT;
        RETURN;
    END IF;

    UPDATE storage.dataelements
        SET element = element || jsonb_build_object('IsRead', _isRead)
        WHERE alternateid = _dataelementGuid AND instanceguid = _instanceGuid
        RETURNING element, storage.dataelements.currentblobversion
            INTO _updatedElement, _currentBlobVersion;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, 'not_found'::TEXT;
        RETURN;
    END IF;

    IF _isRead = FALSE
    THEN
        UPDATE storage.instances
            SET instance = jsonb_set(instance, '{Status, ReadStatus}', '0')
            WHERE alternateid = _instanceGuid
                AND instance -> 'Status' ->> 'ReadStatus' = '1'
                AND NOT EXISTS (
                    SELECT 1 FROM storage.dataelements
                        WHERE element -> 'IsRead' = 'true'
                            AND instanceguid = _instanceGuid
                            AND alternateid <> _dataelementGuid
                );
    END IF;

    RETURN QUERY SELECT _updatedElement, _currentBlobVersion, _currentInstanceVersion, _currentProcessStateVersion, 'ok'::TEXT;
END;
$BODY$;


-- updatedataelement.sql:
CREATE OR REPLACE FUNCTION storage.updatedataelement_v3(
    _dataelementGuid UUID,
    _instanceGuid UUID,
    _elementChanges JSONB,
    _instanceChanges JSONB,
    _isReadChangedToFalse BOOL,
    _lastChanged TIMESTAMPTZ,
    _newcurrentblobversion UUID,
    _expectedcurrentblobversion UUID,
    _ignoreLock BOOL,
    _expectedinstanceversion INT DEFAULT NULL,
    _expectedprocessstateversion INT DEFAULT NULL)
    RETURNS TABLE (updatedElement JSONB, currentblobversion UUID, instanceversion INT, processstateversion INT, currentprocessstatus TEXT, result TEXT)
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _lastChanged6digits TEXT;
    _instanceIsHardDeleted BOOL;
    _currentInstanceVersion INT;
    _currentProcessStateVersion INT;
    _currentProcessStatus TEXT;
    _newInstanceVersion INT;
    _dataElementIsHardDeleted BOOL;
    _dataElementIsLocked BOOL;
    _dataElementCurrentBlobVersion UUID;
BEGIN
    SELECT
        COALESCE((i.instance -> 'Status' ->> 'IsHardDeleted')::BOOLEAN, FALSE),
        i.instance_version,
        i.process_state_version,
        COALESCE(i.instance -> 'Process' ->> 'Status', 'idle')
        INTO _instanceIsHardDeleted, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus
        FROM storage.instances i
        WHERE i.alternateid = _instanceGuid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, NULL::INT, NULL::INT, NULL::TEXT, 'not_found'::TEXT;
        RETURN;
    END IF;

    IF _expectedinstanceversion IS NOT NULL AND _currentInstanceVersion <> _expectedinstanceversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'instance_version_mismatch'::TEXT;
        RETURN;
    END IF;

    IF _expectedprocessstateversion IS NOT NULL AND _currentProcessStateVersion <> _expectedprocessstateversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'process_state_version_mismatch'::TEXT;
        RETURN;
    END IF;

    IF _instanceIsHardDeleted
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'hard_deleted'::TEXT;
        RETURN;
    END IF;

    SELECT COALESCE((d.element -> 'DeleteStatus' ->> 'IsHardDeleted')::BOOLEAN, FALSE),
        COALESCE((d.element ->> 'Locked')::BOOLEAN, FALSE),
        d.currentblobversion
        INTO _dataElementIsHardDeleted, _dataElementIsLocked, _dataElementCurrentBlobVersion
        FROM storage.dataelements d
        WHERE d.alternateid = _dataelementGuid AND d.instanceguid = _instanceGuid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'not_found'::TEXT;
        RETURN;
    END IF;

    IF _expectedcurrentblobversion IS NOT NULL AND _dataElementCurrentBlobVersion IS DISTINCT FROM _expectedcurrentblobversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'version_mismatch'::TEXT;
        RETURN;
    END IF;

    IF _dataElementIsHardDeleted
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'hard_deleted'::TEXT;
        RETURN;
    END IF;

    IF NOT _ignoreLock AND _dataElementIsLocked
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'locked'::TEXT;
        RETURN;
    END IF;

    IF _lastChanged IS NOT NULL
    THEN
        -- Make sure that lastChanged has the Postgres precision (6 digits). The timestamp from C# DateTime and then json serialize has 7 digits
        _lastChanged6digits = REPLACE((_lastChanged AT TIME ZONE 'UTC')::TEXT, ' ', 'T') || 'Z';
        _elementChanges := _elementChanges || jsonb_set('{"LastChanged":""}', '{LastChanged}', to_jsonb(_lastChanged6digits));
    END IF;

    IF _currentProcessStatus <> 'idle'
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::UUID, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'process_status_conflict'::TEXT;
        RETURN;
    END IF;

    IF _newcurrentblobversion IS NOT NULL
    THEN
        -- Only one version per data element may be attached, and the partial unique index
        -- enforcing that is checked per statement, so the predecessor is detached first.
        UPDATE storage.dataelementblobversions
            SET detachedat = NOW()
            WHERE instanceguid = _instanceGuid
                AND dataelementid = _dataelementGuid
                AND detachedat IS NULL;

        UPDATE storage.dataelementblobversions
            SET detachedat = NULL
            WHERE id = _newcurrentblobversion
                AND instanceguid = _instanceGuid
                AND dataelementid = _dataelementGuid
                AND detachedat IS NOT NULL;
    END IF;

    UPDATE storage.instances
        SET lastchanged = COALESCE(_lastChanged, lastchanged),
            instance_version = instance_version + 1,
            instance = (
                CASE
                    WHEN _isReadChangedToFalse = true AND
                        (SELECT COUNT(*) FROM storage.dataelements
                            WHERE element -> 'IsRead' = 'true' AND instanceguid = _instanceGuid AND alternateid <> _dataelementGuid) = 0
                        AND instance -> 'Status' ->> 'ReadStatus' = '1'
                    THEN jsonb_set(instance, '{Status, ReadStatus}', '0')
                    ELSE instance
                END
            )
            || CASE
                WHEN _lastChanged IS NOT NULL
                THEN _instanceChanges || jsonb_set('{"LastChanged":""}', '{LastChanged}', to_jsonb(_lastChanged6digits))
                ELSE '{}'::JSONB
            END
        WHERE alternateid = _instanceGuid
        RETURNING storage.instances.instance_version INTO _newInstanceVersion;

    RETURN QUERY
        UPDATE storage.dataelements
            SET element = element || _elementChanges,
                currentblobversion = COALESCE(_newcurrentblobversion, storage.dataelements.currentblobversion)
            WHERE alternateid = _dataelementGuid AND instanceguid = _instanceGuid
            RETURNING element, storage.dataelements.currentblobversion, _newInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'ok'::TEXT;
END;
$BODY$;


-- updateinstance_readstatus.sql:
CREATE OR REPLACE FUNCTION storage.updateinstance_readstatus(
        _alternateid UUID,
        _readstatus INT)
    RETURNS TABLE (updatedInstance JSONB, instanceversion INT, processstateversion INT, result TEXT)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
    RETURN QUERY
        UPDATE storage.instances SET
            instance = jsonb_set(
                instance,
                '{Status}',
                CASE WHEN jsonb_typeof(instance -> 'Status') = 'object' THEN
                    instance -> 'Status' || jsonb_build_object('ReadStatus', _readstatus)
                ELSE
                    jsonb_build_object('ReadStatus', _readstatus)
                END
            )
        WHERE _alternateid = alternateid
        RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, 'ok'::TEXT;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::INT, NULL::INT, 'not_found'::TEXT;
    END IF;
END;
$BODY$;


-- updateinstance.sql:
CREATE OR REPLACE FUNCTION storage.updateinstance_v4(
        _alternateid UUID,
        _toplevelsimpleprops JSONB,
        _datavalues JSONB,
        _completeconfirmations JSONB,
        _presentationtexts JSONB,
        _status JSONB,
        _substatus JSONB,
        _process JSONB,
        _lastchanged TIMESTAMPTZ,
        _taskid TEXT,
        _confirmed BOOLEAN DEFAULT NULL,
        _expectedinstanceversion INT DEFAULT NULL,
        _expectedprocessstateversion INT DEFAULT NULL)
    RETURNS TABLE (updatedInstance JSONB, instanceversion INT, processstateversion INT, currentprocessstatus TEXT, result TEXT)
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    _currentInstance JSONB;
    _currentInstanceVersion INT;
    _currentProcessStateVersion INT;
    _currentProcessStatus TEXT;
BEGIN
    SELECT i.instance, i.instance_version, i.process_state_version
        INTO _currentInstance, _currentInstanceVersion, _currentProcessStateVersion
        FROM storage.instances i
        WHERE i.alternateid = _alternateid
        FOR UPDATE;

    IF NOT FOUND
    THEN
        RETURN QUERY SELECT NULL::JSONB, NULL::INT, NULL::INT, NULL::TEXT, 'not_found'::TEXT;
        RETURN;
    END IF;

    _currentProcessStatus := COALESCE(_currentInstance -> 'Process' ->> 'Status', 'idle');

    IF _expectedinstanceversion IS NOT NULL AND _currentInstanceVersion <> _expectedinstanceversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'instance_version_mismatch'::TEXT;
        RETURN;
    END IF;

    IF _expectedprocessstateversion IS NOT NULL AND _currentProcessStateVersion <> _expectedprocessstateversion
    THEN
        RETURN QUERY SELECT NULL::JSONB, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'process_state_version_mismatch'::TEXT;
        RETURN;
    END IF;

    IF _currentProcessStatus <> 'idle'
    THEN
        RETURN QUERY SELECT NULL::JSONB, _currentInstanceVersion, _currentProcessStateVersion, _currentProcessStatus, 'process_status_conflict'::TEXT;
        RETURN;
    END IF;

    _toplevelsimpleprops := COALESCE(_toplevelsimpleprops, '{}'::JSONB) - 'Process';

    IF _datavalues IS NOT NULL THEN
        RETURN QUERY
            UPDATE storage.instances SET
                instance = instance || _toplevelsimpleprops ||
                    jsonb_strip_nulls(
                        jsonb_set(
                            '{"DataValues":""}',
                            '{DataValues}',
                            CASE WHEN instance -> 'DataValues' IS NOT NULL THEN
                                instance -> 'DataValues' || _datavalues
                            ELSE
                                _datavalues
                            END
                        )
                    ),
                lastchanged = _lastchanged,
                instance_version = instance_version + 1,
                confirmed = CASE WHEN _confirmed IS NULL THEN confirmed ELSE _confirmed END
            WHERE _alternateid = alternateid
            RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, _currentProcessStatus, 'ok'::TEXT;
    ELSIF _presentationtexts IS NOT NULL THEN
        RETURN QUERY
            UPDATE storage.instances SET
                instance = instance || _toplevelsimpleprops ||
                    jsonb_strip_nulls(
                        jsonb_set(
                            '{"PresentationTexts":""}',
                            '{PresentationTexts}',
                            CASE WHEN instance -> 'PresentationTexts' IS NOT NULL THEN
                                instance -> 'PresentationTexts' || _presentationtexts
                            ELSE
                                _presentationtexts
                            END
                        )
                    ),
                lastchanged = _lastchanged,
                instance_version = instance_version + 1,
                confirmed = CASE WHEN _confirmed IS NULL THEN confirmed ELSE _confirmed END
            WHERE _alternateid = alternateid
            RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, _currentProcessStatus, 'ok'::TEXT;
    ELSIF _completeconfirmations IS NOT NULL THEN
        RETURN QUERY
            UPDATE storage.instances SET
                instance = instance || _toplevelsimpleprops ||
                    jsonb_set(
                        '{"CompleteConfirmations":""}',
                        '{CompleteConfirmations}',
                        CASE WHEN instance -> 'CompleteConfirmations' IS NOT NULL THEN
                            instance -> 'CompleteConfirmations' || _completeconfirmations
                        ELSE
                            _completeconfirmations
                        END
                    ),
                lastchanged = _lastchanged,
                instance_version = instance_version + 1,
                confirmed = CASE WHEN _confirmed IS NULL THEN confirmed ELSE _confirmed END
            WHERE _alternateid = alternateid
            RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, _currentProcessStatus, 'ok'::TEXT;
    ELSIF _status IS NOT NULL AND _process IS NULL THEN
        RETURN QUERY
            UPDATE storage.instances SET
                instance = instance ||
                    jsonb_set(
                        instance || _toplevelsimpleprops,
                        '{Status}',
                        CASE WHEN instance -> 'Status' IS NOT NULL THEN
                            instance -> 'Status' || _status
                        ELSE
                            _status
                        END
                    ),
                lastchanged = _lastchanged,
                instance_version = instance_version + 1,
                confirmed = CASE WHEN _confirmed IS NULL THEN confirmed ELSE _confirmed END
            WHERE _alternateid = alternateid
            RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, _currentProcessStatus, 'ok'::TEXT;
    ELSIF _substatus IS NOT NULL THEN
        RETURN QUERY
            UPDATE storage.instances SET
                instance = instance ||
                    jsonb_set(
                        instance || _toplevelsimpleprops,
                        '{Status, Substatus}',
                        jsonb_strip_nulls(_substatus)
                    ),
                lastchanged = _lastchanged,
                instance_version = instance_version + 1,
                confirmed = CASE WHEN _confirmed IS NULL THEN confirmed ELSE _confirmed END
            WHERE _alternateid = alternateid
            RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, _currentProcessStatus, 'ok'::TEXT;
    ELSIF _process IS NOT NULL AND _status IS NOT NULL THEN
        RETURN QUERY
            UPDATE storage.instances SET
                instance = instance ||
                    jsonb_set(
                        instance || _toplevelsimpleprops,
                        '{Process}',
                        jsonb_strip_nulls(_process)
                    ) ||
                    jsonb_set(
                        '{"Status":""}',
                        '{Status}',
                        CASE WHEN instance -> 'Status' IS NOT NULL THEN
                            instance -> 'Status' || _status
                        ELSE
                            _status
                        END
                    ),
                lastchanged = _lastchanged,
                instance_version = instance_version + 1,
                process_state_version = process_state_version + 1,
                confirmed = CASE WHEN _confirmed IS NULL THEN confirmed ELSE _confirmed END,
                taskid = _taskid
            WHERE _alternateid = alternateid
            RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, _currentProcessStatus, 'ok'::TEXT;
    ELSIF _process IS NOT NULL THEN
        RETURN QUERY
            UPDATE storage.instances SET
                instance = instance ||
                    jsonb_set(
                        instance || _toplevelsimpleprops,
                        '{Process}',
                        jsonb_strip_nulls(_process)
                    ),
                lastchanged = _lastchanged,
                instance_version = instance_version + 1,
                process_state_version = process_state_version + 1,
                confirmed = CASE WHEN _confirmed IS NULL THEN confirmed ELSE _confirmed END,
                taskid = _taskid
            WHERE _alternateid = alternateid
            RETURNING instance, storage.instances.instance_version, storage.instances.process_state_version, _currentProcessStatus, 'ok'::TEXT;
    ELSE
        RAISE EXCEPTION 'Unexpected parameters to update instance';
    END IF;
END;
$BODY$;


-- updateinstancelock.sql:
CREATE OR REPLACE PROCEDURE storage.updateinstancelock(
    _id BIGINT,
    _instanceinternalid BIGINT,
    _ttl INTERVAL,
    _secrethash BYTEA,
    INOUT _result TEXT DEFAULT NULL
)
LANGUAGE plpgsql
AS $BODY$
DECLARE
    _locked_until TIMESTAMPTZ;
    _stored_hash BYTEA;
    _now TIMESTAMPTZ;
BEGIN
    PERFORM pg_advisory_xact_lock(_instanceinternalid);

    SELECT lockeduntil, secrethash FROM storage.instancelocks
    WHERE id = _id
    AND instanceinternalid = _instanceinternalid
    INTO _locked_until, _stored_hash;

    IF _locked_until IS null THEN
        _result := 'lock_not_found';
        RETURN;
    END IF;

    IF _stored_hash != _secrethash THEN
        _result := 'token_mismatch';
        RETURN;
    END IF;

    SELECT clock_timestamp()
    INTO _now;

    IF _locked_until <= _now THEN
        _result := 'lock_expired';
        RETURN;
    END IF;

    UPDATE storage.instancelocks
    SET lockeduntil = _now + _ttl
    WHERE id = _id;

    _result := 'ok';
END;
$BODY$;


-- updatemigrationstatecompleted.sql:
CREATE OR REPLACE PROCEDURE storage.updatemigrationstatecompleted (_instanceguid UUID)
    LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	UPDATE storage.a1migrationstate SET completed = now()
		WHERE instanceguid = _instanceguid;
	UPDATE storage.a2migrationstate SET completed = now()
		WHERE instanceguid = _instanceguid;
END;
$BODY$;

