CREATE TABLE IF NOT EXISTS storage.a1migrationstate
(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	a1archivereference BIGINT UNIQUE NOT NULL,
	instanceguid UUID UNIQUE NULL,
	started TIMESTAMPTZ NULL,
	completed TIMESTAMPTZ NULL
)
TABLESPACE pg_default;

GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA storage TO platform_storage;
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA storage TO platform_storage_admin;