using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Altinn.Platform.Storage.Models;

namespace Altinn.Platform.Storage.Services;

/// <summary>
/// Service responsible for removing data elements that were generated by a
/// specific process task, typically invoked when that task is (re-)entered.
/// </summary>
public interface IProcessDataCleanupService
{
    /// <summary>
    /// Finds all data elements on <paramref name="instanceInternal"/> whose
    /// <see cref="DataElementInternal.References"/> contain a reference matching
    /// <c>{Relation = GeneratedFrom, ValueType = Task, Value = taskId}</c>.
    /// </summary>
    /// <param name="instanceInternal">
    /// The instance whose data elements should be evaluated. The wrapped instance is not mutated.
    /// </param>
    /// <param name="taskId">The id of the task that the instance is entering.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>The data elements to delete in the aggregate process transition.</returns>
    Task<IReadOnlyList<DataElementInternal>> GetGeneratedFromTaskDataElements(
        InstanceInternal instanceInternal,
        string taskId,
        CancellationToken cancellationToken
    );
}
