using System;
using System.Threading;
using System.Threading.Tasks;
using Altinn.Platform.Storage.Interface.Models;
using Altinn.Platform.Storage.Models;

namespace Altinn.Platform.Storage.Services;

/// <summary>
/// Service responsible for removing data elements that were generated by a
/// specific process task, typically invoked when that task is (re-)entered.
/// </summary>
public interface IProcessDataCleanupService
{
    /// <summary>
    /// Deletes all data elements on <paramref name="instanceInternal"/> whose
    /// <see cref="DataElement.References"/> contain a reference matching
    /// <c>{Relation = GeneratedFrom, ValueType = Task, Value = taskId}</c>.
    /// Each delete is best-effort: individual failures are logged and skipped,
    /// not propagated.
    /// </summary>
    /// <remarks>
    /// This operation has a hard dependency on resolving the relevant application and its storage account number,
    /// via <see cref="IApplicationService.GetApplicationOrErrorAsync"/>. A failure with this lookup will result in an
    /// <see cref="InvalidOperationException"/>.
    /// </remarks>
    /// <param name="instanceInternal">
    /// The instance whose data elements should be evaluated. The wrapped <see cref="Instance.Data"/> list is mutated to
    /// remove successfully deleted elements so subsequent persistence reflects the cleanup.
    /// </param>
    /// <param name="taskId">The id of the task that the instance is entering.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>The updated instance metadata with stale data elements removed.</returns>
    /// <exception cref="InvalidOperationException">Error looking up the application's storage account.</exception>
    Task<InstanceInternal> CleanupGeneratedFromTask(
        InstanceInternal instanceInternal,
        string taskId,
        CancellationToken cancellationToken
    );
}
