name: Code test and analysis (fork)
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/build-and-analyze-fork.yml'
      - 'src/**'
      - 'test/Altinn.Platform.Storage.Interface.Tests/**'
      - 'test/UnitTest/**'

jobs:
  test:
    if: github.actor == 'dependabot[bot]' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:16@sha256:e17e86066e5ef83e0952a9347f5c792b7ece00972e2aa787a6986f471b3dd3d5
        env:
          PGHOST: localhost
          POSTGRES_USER: platform_storage_admin
          POSTGRES_PASSWORD: Password
          POSTGRES_DB: storagedb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            10.0.x
      - name: Set up Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          persist-credentials: false
      - name: Setup PostgreSQL
        run: |
          chmod +x dbsetup.sh
          ./dbsetup.sh
      - name: Restart database to enable config changes
        run: |
          docker restart $(docker ps -q)
      - name: Build & Test
        run: |
          dotnet build Altinn.Platform.Storage.slnx -v q

          dotnet test Altinn.Platform.Storage.slnx \
          -v q \
          --collect:"XPlat Code Coverage" /p:Exclude="**/Program.cs" \
          --results-directory TestResults/ \
          --logger "trx;" \
          --configuration release \
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: TestResults
          path: '**/TestResults/*.trx'
