name: Regression Test - AT22

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 1-5'

jobs:
  at22:
    uses: ./.github/workflows/regression-test-ATX.yml
    with:
      environment: AT22
    secrets: inherit