name: Regression test - AT

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  regression-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: ${{ inputs.environment }}
    env: # Shared environment variables in k6 scripts
      altinn_env: ${{ inputs.environment }}
      apimSubsKey: ${{ secrets.APIM_SUBSKEY }}
      app: ${{ vars.APP }}
      org: ${{ vars.ORG }}
      pid: ${{ secrets.TESTIDP_TENOR_PID }}
      testidppwd: ${{ secrets.TESTIDP_PASSWORD }}
      runFullTestSet: true
      tokenGeneratorUserName: ${{ secrets.TOKENGENERATOR_USERNAME }}
      tokenGeneratorUserPwd: ${{ secrets.TOKENGENERATOR_USERPASSWORD }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: grafana/setup-k6-action@db07bd9765aac508ef18982e52ab937fe633a065 # v1.2.1
      - name: Run regression tests for endpoint 'applications'
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/applications.js
          inspect-flags: -e altinn_env=${{ inputs.environment }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined

      - name: Run regression tests for endpoint 'instances'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/instances.js
          flags: -e orgNumber=${{ secrets.ORG_NUMBER }} -e orgPartyId=${{ secrets.ORG_PARTY_ID }}
          inspect-flags: -e altinn_env=${{ inputs.environment }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'instances/sbl'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/messageboxinstances.js
          flags: -e apimSblSubsKey=${{ secrets.APIM_SBL_SUBSKEY }}
          inspect-flags: -e altinn_env=${{ inputs.environment }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'data'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/data.js
          inspect-flags: -e altinn_env=${{ inputs.environment }} -e app=${{ vars.APP }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'process'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/process.js
          inspect-flags: -e altinn_env=${{ inputs.environment }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'sign'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/sign.js
          inspect-flags: -e altinn_env=${{ inputs.environment }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'texts'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/texts.js
          inspect-flags: -e altinn_env=${{ inputs.environment }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined
  slack-notify:
    if: failure()
    needs: regression-tests
    uses: ./.github/workflows/send-slack-warning.yml
    permissions: {}
    with:
      warning-message: 'Storage regression test failure in ${{ inputs.environment }}'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
