name: Regression Test - AT23

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 1-5'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  at23:
    uses: ./.github/workflows/regression-test-ATX.yml
    with:
      environment: AT23
    secrets: inherit