name: Regression test - TT02

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'

permissions:
  contents: read

jobs:
  regression-tests:
    environment: TT02
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env: # Shared environment variables in k6 scripts
      altinn_env: TT02
      apimSubsKey: ${{ secrets.APIM_SUBSKEY }}
      app: ${{ vars.APP }}
      org: ${{ vars.ORG }}
      runFullTestSet: true
      pid: ${{ secrets.TESTIDP_TENOR_PID }}
      testidppwd: ${{ secrets.TESTIDP_PASSWORD }}
      encodedJwk: ${{ secrets.MP_ENCODEDJWK }}
      mpClientId: ${{ secrets.MP_CLIENT_ID }}
      mpKid: ${{ secrets.MP_KID }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: grafana/setup-k6-action@db07bd9765aac508ef18982e52ab937fe633a065 # v1.2.1
      - name: Run regression tests for endpoint 'applications'
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/applications.js
          inspect-flags: -e altinn_env=TT02 # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'instances'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/instances.js
          flags: -e orgNumber=${{ secrets.ORG_NUMBER }} -e orgPartyId=${{ secrets.ORG_PARTY_ID }}
          inspect-flags: -e altinn_env=TT02 # Supplies the value for pre-run validation, when env vars / flags are not yet defined

      - name: Run regression tests for endpoint 'instances/sbl'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/messageboxinstances.js
          flags: -e apimSblSubsKey=${{ secrets.APIM_SBL_SUBSKEY }}
          inspect-flags: -e altinn_env=TT02 # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'data'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/data.js
          inspect-flags: -e altinn_env=TT02 -e app=${{ vars.APP }} # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'process'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/process.js
          inspect-flags: -e altinn_env=TT02 # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'sign'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/sign.js
          inspect-flags: -e altinn_env=TT02 # Supplies the value for pre-run validation, when env vars / flags are not yet defined
      - name: Run regression tests for endpoint 'texts'
        if: always()
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: test/k6/src/tests/texts.js
          inspect-flags: -e altinn_env=TT02 # Supplies the value for pre-run validation, when env vars / flags are not yet defined
  slack-notify:
    if: failure()
    needs: regression-tests
    uses: ./.github/workflows/send-slack-warning.yml
    permissions: {}
    with:
      warning-message: 'Storage regression test failure in TT02'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROD }}